### ISSUE TITLE
Rust website/docs wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1011]
### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Show the standalone installers for earlier releases.
    + Useful for developers and users requiring older versions for kernel compilation purposes.
    + Issue: https://github.com/rust-lang/rust-forge/issues/676.
    + PR: https://github.com/rust-lang/rust-forge/pull/733.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Slightly different `rustup` instructions compared to rust-lang.org's Install page.
    + Useful for giving a single link in our Quick Start guide.
    + Issue: https://github.com/rust-lang/rust-forge/issues/684.
    + PR: https://github.com/rust-lang/www.rust-lang.org/pull/1823.
    + PR: https://github.com/rust-lang/rust-forge/pull/688.
    + PR: https://github.com/rust-lang/rustup/pull/3385.

  - [x] Fix duplicate Rust 1.8.0 in the archive stable version installers page.
    + PR: https://github.com/rust-lang/rust-forge/pull/770.

**Comment by microcassidy** [comment]
https://static.rust-lang.org/dist/YYYY-MM-DD/ 

[issue](https://github.com/rust-lang/rust/issues/14796#issuecomment-62053531)

**Comment by ojeda** [comment]
@xuky76 What do you mean? That URLs like that could be used to show the table?

**Comment by yerke** [comment]
@ojeda do you need standalone installers for stable versions earlier than 1.8? I imagine not, right?
All others are now covered in https://forge.rust-lang.org/infra/archive-stable-version-installers.html

**Comment by ojeda** [comment]
Thanks for asking!

Yeah, Rust for Linux does not need them. We are more than happy with Rust 1.62.0 and later, since that is the version that the oldest supported LTS that has Rust (which was also the first).

Though perhaps other people/project could perhaps want them for historical reasons, e.g. Compiler Explorer currently has all major versions since 1.0.0 to play with.

**Comment by ojeda** [comment]
@yerke By the way, I just noticed the page contains Rust 1.8.0 twice.

**Comment by yerke** [comment]
@ojeda oh, thanks for catching it.

**Comment by ojeda** [comment]
My pleasure!

**Comment by yerke** [comment]
@ojeda The issue with the duplicate versions on https://forge.rust-lang.org/infra/archive-stable-version-installers.html was fixed in https://github.com/rust-lang/rust-forge/pull/770.

**Comment by ojeda** [comment]
Thanks! Added above for reference. I see you are also adding even pre-1.8.0 versions -- we don't need anything that old anyway, but thanks for that too!

**Comment by yerke** [comment]
[PR](https://github.com/rust-lang/rust-forge/pull/771) to add pre-1.8.0 versions is merged. Now you see all historical stable Rust versions on https://forge.rust-lang.org/infra/archive-stable-version-installers.html.

**Comment by ojeda** [comment]
Thanks!
