### ISSUE TITLE
rust-analyzer wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1051]
### Required (we almost certainly want them)

  - [ ] `discoverConfig`.
     + Details/discussion: https://github.com/rust-lang/rust-analyzer/issues/17816#issuecomment-2277367909.
     + PR: https://github.com/rust-lang/rust-analyzer/pull/17246.
     + Issue: https://github.com/rust-lang/rust-analyzer/issues/17537.
     + Issue: https://github.com/rust-lang/rust-analyzer/issues/4604.

  - [ ] Edition 2024 support.
    + Our plan is to migrate to Edition 2024 as soon as possible (unless a blocker is found, of course).
    + Issue: https://github.com/rust-lang/rust-analyzer/issues/16146.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] A way to avoid exploding the size of `rust-project.json` with thousands of `cfg`s defined repeatedly per crate.
    + Issue: https://github.com/rust-lang/rust-analyzer/issues/17815.
    + If we end up using the `discoverConfig` support (and we replace completely `rust-project.json` -- see also a few notes at https://github.com/rust-lang/rust-analyzer/issues/17816#issuecomment-2284607312), then we would not need this anymore, and rust-analyzer will likely remove it: https://github.com/rust-lang/rust-analyzer/pull/17857#issuecomment-2306727031.
    + PR: https://github.com/rust-lang/rust-analyzer/pull/17857.

  - [x] Support `.rust-project.json` (i.e. hidden).
    + Issue: https://github.com/rust-lang/rust-analyzer/issues/17816.
    + PR: https://github.com/rust-lang/rust-analyzer/pull/17818 (1.82.0).

---

### Required (we almost certainly want them)

  - [ ] Support goto-definition for `include!(concat!(env!("OBJTREE"), "/..._generated.rs"));`
    + Potentially the cause of https://github.com/Rust-for-Linux/linux/issues/1050.
    + Issue: https://github.com/rust-lang/rust-analyzer/issues/15836.

### Nice to have (probably not critical, we could workaround if needed, etc.)

  - [ ] Limitations around `#[path = "..."]`.
    + A possible workaround is to use a symlink.
    + Issue: https://github.com/rust-lang/rust-analyzer/issues/3898.
    + Lore: https://lore.kernel.org/rust-for-linux/20250319-pin-init-internal-quote-v1-1-19de6a33a257@gmail.com/.

### Done (stabilized, fixed, or not needed anymore, etc.)
