### ISSUE TITLE
Rust CI wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1080]
Note: the policy for the Rust for Linux CI job in upstream Rust is at https://rustc-dev-guide.rust-lang.org/tests/rust-for-linux.html.

### Required (we almost certainly want them)

  - [ ] Run `objtool` to detect CFI violations.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] The kernel in the Rust CI.
    + Ideally in the pre-merge CI.
    + Draft policy from RustNL: https://hackmd.io/@rustnl-2024-unconf/HkutiwyQR.
    + PR: https://github.com/rust-lang/rust/pull/125209 (2024-06-10).
    + PR (Rust for Linux ping group - initial marker team to list members): https://github.com/rust-lang/team/pull/1457.
    + PR (Rust for Linux ping group - actual ping group): https://github.com/rust-lang/rust/pull/125375.
    + PR (Rust for Linux ping group - docs on dev guide): https://github.com/rust-lang/rustc-dev-guide/pull/1984.
    + PR (Rust for Linux ping group - fill marker team): https://github.com/rust-lang/team/pull/1465.
    + PR (Rust for Linux ping group - fill marker team 2): https://github.com/rust-lang/team/pull/1466.
    + PR (Renamed CI job): https://github.com/rust-lang/rust/pull/127023.
    + PR (Documentation about policy): https://github.com/rust-lang/rustc-dev-guide/pull/2004.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Testing.20Rust.20for.20Linux.20in.20our.20CI.
    + Zulip (question about process, long after it was added): https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/RFL.20CI.20Job.

  - [x] Move RFL job forward to v6.11-rc1.
    + PR: https://github.com/rust-lang/rust/pull/128322.

  - [x] Build the generated doctests and documentation.
    + PR: https://github.com/rust-lang/rust/pull/128367.

  - [x] Add a few more tools and steps (Clippy, `rustfmt`, `-Zunpretty=expanded`).
    + PR: https://github.com/rust-lang/rust/pull/128928.

  - [x] Move RFL job forward to v6.12-rc2.
    + PR: https://github.com/rust-lang/rust/pull/131378.

  - [x] Move RFL job forward to `rust-next` (i.e. to a commit, temporarily) to avoid using `feature(receiver_trait)`.
    + PR: https://github.com/rust-lang/rust/pull/132058.
    + Needed for: https://github.com/rust-lang/rust/pull/130225.

  - [x] Update and make the policy official.
    + PR: https://github.com/rust-lang/rustc-dev-guide/pull/2108.

  - [x] Move RFL job forward to v6.13-rc1.
    + PR: https://github.com/rust-lang/rust/pull/133827.

  - [x] Move RFL job forward to v6.14-rc3.
    + PR: https://github.com/rust-lang/rust/pull/137169.

  - [x] Ping group: remove Wedson.
    + PR: https://github.com/rust-lang/team/pull/1658.

  - [x] Ping group: add Danilo.
    + PR: https://github.com/rust-lang/team/pull/1659.

  - [x] Re-enable the Rust for Linux job using `PATH`.
    + PR: https://github.com/rust-lang/rust/pull/137947.

  - [x] Move RFL job forward to v6.15-rc4.
    + PR: https://github.com/rust-lang/rust/pull/140470.

  - [x] Fix Rust for Linux ping group.
    + PR: https://github.com/rust-lang/rust/pull/141139.
    + Related issue (detect misconfigurations): https://github.com/rust-lang/triagebot/issues/1992.

  - [x] Move RFL job back to a tag when the fix to use Edition 2024 for `core` in Rust >= 1.87.0 is in place.
    + Issue: https://github.com/Rust-for-Linux/linux/issues/1163.
    + Affected PR: https://github.com/rust-lang/rust/pull/140966.
    + PR that changed the Edition used: https://github.com/rust-lang/rust/pull/138162 (1.87).

  - [x] Move RFL job forward to v6.16-rc1.
    + PR: https://github.com/rust-lang/rust/pull/142218.

  - [x] Retroactive MCP for the CI job.
    + MCP: https://github.com/rust-lang/compiler-team/issues/874.

  - [x] Move RFL job forward to v6.17-rc3 plus 2 commits.
    + PR: https://github.com/rust-lang/rust/pull/146154.

  - [x] Move RFL job forward to v6.17-rc5 to remove temporary commits.
    + PR: https://github.com/rust-lang/rust/pull/146368.

  - [x] Add a CI job that runs a subset of UI tests with the GCC backend.
    + PR: https://github.com/rust-lang/rust/pull/146414.

  - [x] Move RFL job forward to v7.0.
    + PR: https://github.com/rust-lang/rust/pull/155833.

  - [x] Move RFL job forward to v7.1-rc1.
    + PR: https://github.com/rust-lang/rust/pull/155876.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

**Comment by keys-i** [comment]
is this done?

**Comment by ojeda** [comment]
These are meta-issues to hold live lists, i.e. they can grow over time. We could close on 0 and reopen if something gets added, but I am not sure how that would be useful.

**Comment by Conan-Kudo** [comment]
Do we test Clang + LTO alongside the other modes (Clang without LTO, GCC, etc.)?

**Comment by ojeda** [comment]
Only a single, basic built-test is done, and only for the Rust side of the kernel, at least so far. It is mainly meant to catch unintentional changes around unstable features that would break the kernel's build.

**Comment by davidtwco** [comment]
In the 23/10/2024 Project-RfL meeting, we discussed wanting the compiler team to come up with an official policy on what we'll do when the CI job breaks, but I think what [you've already got in the dev guide](https://rustc-dev-guide.rust-lang.org/tests/rust-for-linux.html) is pretty good and I'm happy for us to stick with that. If we end up finding out that policy doesn't work then we can change it but it seems like a very sensible starting point to me. I'll update the dev guide to remove "unofficial".

cc @wesleywiser

**Comment by ojeda** [comment]
Thanks for taking a look David. That is great -- if we can help with something or something needs changing in the instructions/guidelines, please of course ping us, we are happy to adjust. The CI job has worked great so far for both Rust and the kernel, as far as I can tell.
