### ISSUE TITLE
`pahole` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1096]
Note: see as well the `pahole` Rust cases: https://github.com/Rust-for-Linux/pahole-rust-cases.

### Required (we almost certainly want them)

  - [ ] Support `DW_TAG_variant_part`.
    + Currently it is the last warning for Rust build, with:
      ```console
      ⬢[acme@toolbox linux]$ pahole -C '<kernel::str::RawFormatter as core::fmt::Write>::{vtable_type}' ../build/rust-kernel/rust/kernel.o
      die__process_class: tag not supported 0x33 (variant_part) at <14f43>!
      struct <kernel::str::RawFormatter as core::fmt::Write>::{vtable_type} {
              () *                       drop_in_place __attribute__((__aligned__(8))); /*     0     8 */
              usize                      size __attribute__((__aligned__(8))); /*     8     8 */
              usize                      align __attribute__((__aligned__(8))); /*    16     8 */
              () *                       __method3 __attribute__((__aligned__(8))); /*    24     8 */
              () *                       __method4 __attribute__((__aligned__(8))); /*    32     8 */
              () *                       __method5 __attribute__((__aligned__(8))); /*    40     8 */
             /* size: 48, cachelines: 1, members: 6 */
              /* forced alignments: 6 */
              /* last cacheline: 48 bytes */
      } __attribute__((__aligned__(8)));
      ```
    + https://github.com/acmel/dwarves/commit/2e8cd6a435d96335c4794794147019369b6a7b6a ("dwarf_loader: Ignore DW_TAG_variant_part for now to fix a segfault") (v1.18).

  - [ ] Support BTF for Rust.
    + https://github.com/acmel/dwarves/commit/431df45378ef00f33bb0f00efa1b9350a5ea62a3 ("btfdiff: Exclude Rust CUs since those are not yet being converted to BTF on the Linux kernel") (v1.25).
    + There is also an effort to support BTF for Rust with LTO by generating BTF directly instead of going through `pahole` -- see https://github.com/Rust-for-Linux/linux/issues/1132.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Do `--lang_exclude` CU filtering earlier.
    + https://github.com/acmel/dwarves/commit/5e3ed3ec2947c69f2bf447857e4dd288ba245529 ("pahole: Do --lang_exclude CU filtering earlier") (v1.28).
    + https://github.com/acmel/dwarves/commit/c46455bb0379fa38fdebec0e5f10a465732238c2 ("dwarf_loader: Allow filtering CUs early in loading") (v1.28).

  - [x] Support `DW_TAG_template_type_param`.
    + https://github.com/acmel/dwarves/commit/8a1e0238ee4005a6e164fb930692f7d4d095128c ("dwarf_loader: Initial support for DW_TAG_template_type_param tag") (v1.28).

  - [x] Support reordering of fields.
    + i.e. avoid assuming structs fields are in order, since Rust's default representation reorders them.
    + https://github.com/acmel/dwarves/commit/c4eb1897d1f3841d291ee39dc969c4212750cf2c ("core: Check that we're adding DW_TAG_member sorted by byte offset") (v1.25).

  - [x] Support `--lang` and `--lang_exclude`.
    + Used by: commit c1177979af9c ("btf, scripts: Exclude Rust CUs with pahole").
    + https://github.com/acmel/dwarves/commit/8ee363790b7437283c53090a85a9fec2f0b0fbc4 ("pahole: Introduce --lang to ask for only compilation units written in some languages") (v1.24).
    + https://github.com/acmel/dwarves/commit/49358dfe2aaae4e90b072332c3e324019826783f ("pahole: Add --lang_exclude to allow skipping compilation units written in some languages") (v1.24).

---

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Fix sorting of Rust structs.
    + https://github.com/acmel/dwarves/commit/1231b6b9b4d88e0084bef4254eb1a05eb9935c99 ("dwarf_loader: Fix sorting of Rust structs") (v1.25).
