### ISSUE TITLE
Distributions wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1127]
### Done (stabilized, fixed, not needed anymore, etc.)

---

### Required (we almost certainly want them)

  - [ ] Ubuntu non-LTS 24.10: failure building kernel with tracepoints code (due to `bindgen` <= 0.69.5 && `libclang` >= 19.1).
    + Bug report: https://bugs.launchpad.net/ubuntu/+source/rust-bindgen-cli/+bug/2086639.
    + List: archives do not show it?
    + Patch: https://lore.kernel.org/rust-for-linux/20241111201607.653149-1-ojeda@kernel.org/.

  - [ ] Ubuntu LTS 24.04: failure building kernel due to the interior nulls issue (due to `bindgen` == 0.66.x, i.e. not present in < 0.66 nor >= 0.67).
    + A workaround is using the `bindgen-0.65` package, which is what we have in the Quick Start instructions.
    + Bug report: https://bugs.launchpad.net/ubuntu/+source/rust-bindgen-cli/+bug/2086641.
    + Commit: 981ad93c89a3 ("rust: warn about `bindgen` versions 0.66.0 and 0.66.1").

  - [ ] Ubuntu: versioned toolchains (e.g. `rustc-1.80-src`): missing `lib/rustlib/src` in sysroot.
    + This forces developers to tweak `RUST_LIB_SRC` (and us to give custom instructions for Ubuntu in our Quick Start guide: https://docs.kernel.org/next/rust/quick-start.html#ubuntu, see commit 38f022b0787b ("docs: rust: quick-start: add Ubuntu")).
    + Bug report: https://bugs.launchpad.net/ubuntu/+source/rustc-1.80/+bug/2090791.
    + Fixed in 1.80.1+dfsg0ubuntu1-0ubuntu2 (currently only in Ubuntu 25.04: https://packages.ubuntu.com/search?keywords=rustc-1.80&searchon=names&suite=all&section=all).
    + Fixed in 1.81.0+dfsg0ubuntu1-0ubuntu2 (currently only in Ubuntu 25.04: https://packages.ubuntu.com/search?keywords=rustc-1.81&searchon=names&suite=all&section=all).

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Fedora 41: failure building kernel with tracepoints code (due to `bindgen` <= 0.69.5 && `libclang` >= 19.1).
    + Update: https://bodhi.fedoraproject.org/updates/FEDORA-2024-77ec58c3a3.
    + Patch: https://lore.kernel.org/rust-for-linux/20241111201607.653149-1-ojeda@kernel.org/.

  - [x] Debian Sid: failure building kernel with tracepoints code (due to `bindgen` <= 0.69.5 && `libclang` >= 19.1).
    + Bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1086510.
    + Backport PR (if there is no upgrade to 0.70.x): https://salsa.debian.org/rust-team/debcargo-conf/-/merge_requests/771.
    + List: https://alioth-lists.debian.net/pipermail/pkg-rust-maintainers/2024-October/049880.html.
    + Patch: https://lore.kernel.org/rust-for-linux/20241111201607.653149-1-ojeda@kernel.org/.

  - [x] Debian: transitioning to `bindgen` 0.70 (from 0.66 with backports).
    + Issue: https://salsa.debian.org/rust-team/debcargo-conf/-/issues/89.
    + PR: https://salsa.debian.org/rust-team/debcargo-conf/-/merge_requests/774.
