### ISSUE TITLE
Clippy wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#349]
Please see as well:

  - https://github.com/Rust-for-Linux/linux/issues/350 (i.e. some lints may make sense in Clippy, some in `rustdoc`).

  - https://github.com/rust-lang/rust-project-goals/pull/483: proposed Rust project goal on safety-critical lints, including potential call graph / cross-crate ones, which would overlap with Klint ones. @nbdd0121 suggests extracting part of the linting infrastructure to a library that projects like Clippy and Klint could use.

### Required (we almost certainly want them)

  - [ ] Lint to require `// PANIC: ...` comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15861.
    + Issue (duplicate with more context): https://github.com/rust-lang/rust-clippy/issues/15895.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15969.
    + Cc: @blyxyas @hcbarker.

  - [ ] Lint to detect unneeded `// PANIC: ...` comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15896.
    + The dual to the one that requires it (see above).

  - [ ] Lint to require `// CAST: ...` comments for `as` casts.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15963.
    + PR: https://github.com/rust-lang/rust-clippy/pull/16682.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72m9ms-OznWQ5+4_JvAs4yruwgBRcm1u0gCAnasqO8uJOA@mail.gmail.com/.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/channel/577190-clippy.2Ffcp/topic/FCP.20rust-clippy.2316682.3A.20Add.20.60undocumented_as_casts.60.20lint/near/577930515.
    + Cc: @blyxyas @hcbarker @charlieHsiuC.

  - [ ] Lint to require `// CAST: ...` comments for pointer casts.
    + See the one for `as` casts.

  - [ ] Lint to detect unneeded `// CAST: ...` comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15964.
    + The dual to the one(s) that require it (see above), i.e. `as` casts and pointer casts.

  - [ ] Lint to require `// ORDERING: ...` comments for atomic operations (or, more generally, methods that take `Ordering` parameters).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/16073.
    + Lore: https://lore.kernel.org/rust-for-linux/aRIY6Pc--rlrJuCN@tardis.local/.
    + Cc: @blyxyas @hcbarker @fbq.

  - [ ] Lint to detect unneeded `// ORDERING: ...` comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/16074.
    + The dual to the one that requires it (see above).

  - [ ] Lint to require `// CALC: ...` comments for non-trivial/chained arithmetic operations that do not use the operators.
    + Given a certain threshold of complexity with checked/saturation/... arithmetic, require a math-like expression on top as a comment. For instance:

      ```rust
      // CALC: `imem_load_size + interface_offset`.
      let hdr_offset = desc
          .imem_load_size()
          .checked_add(desc.interface_offset())
          .map(usize::from_safe_cast)
          .ok_or(EINVAL)?;
      ```

    + Ideally, the lint would even check the expression given matches the expanded form below.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72nhzix4Dr9_gbaFwZQQq=3cDY=oAYVgG5hDAmMgaYKQJg@mail.gmail.com/.

  - [ ] Lint to detect unneeded `// CALC: ...` comments.
    + The dual to the one that requires it (see above).

  - [ ] Lint to catch `#[no_mangle]` on non-`repr(C)` `pub static`s.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11219.
    + PR: https://github.com/rust-lang/rust-clippy/pull/11253.
    + Related (Rust language) PR: https://github.com/rust-lang/rust/pull/114201 (1.74).

  - [ ] Support custom `dbg!`s in the `dbg_macro` lint.
    + We started using it in Rust 1.60, but it stopped working in 1.61 (but it may be intended).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11303.

  - [ ] Lint to catch non-absolute paths in macros, e.g. `core::...` instead of `::core::...`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14472.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14648.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14645.
    + Lore: https://lore.kernel.org/rust-for-linux/D8PDWRH06U1X.3JGHP1311BPPY@proton.me/.

  - [ ] Lint to catch unnecessary generics like `Result<()>`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14848.
    + PR: https://github.com/rust-lang/rust-clippy/pull/16123.
    + `checkpatch.pl` issue: https://github.com/Rust-for-Linux/linux/issues/1128.
    + Lore: https://lore.kernel.org/rust-for-linux/DA03Y4OQIZ50.157T5EEVHQVMI@kernel.org/.

  - [ ] Support custom `assert*!`s for lints like `eq_op`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14903.
    + Lore: https://lore.kernel.org/rust-for-linux/20250502215133.1923676-2-ojeda@kernel.org/#Z31rust:kernel:kunit.rs.

  - [ ] Support custom `format!` macros (`#[clippy::format_args]` attribute).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/16833.
    + Docs: https://doc.rust-lang.org/nightly/clippy/attribs.html#clippyformat_args.
    + PR: https://github.com/rust-lang/rust-clippy/pull/9948 (1.85 -- the docs in the PR say one less version but it ended up in 1.85).
    + Lore: https://lore.kernel.org/rust-for-linux/CAJ-ks9nqv30SOiCia8LE6XbKEURNCa9qwwcszsQ0a8FRxR0Msg@mail.gmail.com/.

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] Improved shadowing lints.
    + We currently do not enable any of the `shadow_*` lints. In particular, `shadow_reuse` would lint on many things that are OK for us, especially "top-level" `let ... =`s. Please see the details in https://github.com/rust-lang/rust-clippy/issues/3433#issuecomment-2495547322.
    + It would have already prevented one kernel bug: https://lore.kernel.org/rust-for-linux/20241123-rust-fix-arraylayout-v1-1-197e64c95bd4@asahilina.net/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/3433.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/2890.

  - [ ] Lints that generalize `exit`, `todo`, `mem_forget`, etc.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/8031.

  - [ ] `disallowed_names` support for identifiers.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11306.

  - [ ] Per-path lint levels for `DisallowedPath`-related lints.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11307.

  - [ ] Have a lint against usize-to-u64 casts (or, against *all* integer casts).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/9231.

  - [ ] Make `unnecessary_cast` cover some `core::ffi::c_*` cases.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13494.

  - [ ] `unnecessary_cast` does not trigger with a local but it does with a parameter.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13495.

  - [ ] Ignoring lints added after a given Rust version.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11227.
    + Related: https://github.com/rust-lang/cargo/issues/12495 (about ignoring unknown lints, explicitly passed, when compiling with an older compiler, rather than a new compiler introducing new lints).
    + If we had something like this, then we could consider using `-D` for some lint groups or leaving Clippy's default for some lints in `clippy::all`.

  - [ ] Unsafe attributes support.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13316.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13317.

  - [ ] Avoid inherent methods on generic smart pointers.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11820.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/.60self.60.20receiver.20vs.20associated.20function.20for.20.60Arc.60/near/472175254.

  - [ ] Split `needless_lifetimes`.
    + One "major addition" to the lint added in 1.86.
    + Currently it is the only `clippy::all` lint that we `allow`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13514.
    + Lore: https://lore.kernel.org/rust-for-linux/20241012231300.397010-1-ojeda@kernel.org/.
    + Lore: https://lore.kernel.org/rust-for-linux/20241116181538.369355-1-ojeda@kernel.org/.

  - [ ] Support for `--fix` without Cargo (e.g. inside `clippy-driver`).
    + Using `cargo` (the binary) would be fine if needed, but not if it requires a Cargo-based structure.

  - [ ] `unsafe extern` support.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13560.

  - [ ] Unneeded `rust` as language in `rustdoc`'s documentation examples.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13604.

  - [ ] `manual_div_ceil` suggests change that could alter behaviour.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14333.

  - [ ] Lint to catch docs using `///` instead of `//!`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14402.
    + Example: 8d9b095b8f89 ("samples: rust_misc_device: Provide an example C program to exercise functionality").

  - [ ] Support `msrv` with a list of unstable features to assume (or perhaps a list of lints that ignore the `msrv` field).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14477.

  - [ ] Lint to catch links in normal comments (i.e. `//`) that are not formatted as Markdown autolinks (i.e. `<https://...>`).
    + Should lints like these be part of `rustdoc` in general, like the wish for intra-doc links there?
    + Rust for Linux example issue to clean instances of these: https://github.com/Rust-for-Linux/linux/issues/1153.

  - [ ] Lint to detect unindented triple backquotes in the end of examples.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15023.
    + Example: https://lore.kernel.org/rust-for-linux/20250609-topics-tyr-regulator-v4-1-b4fdcf1385a7@collabora.com/.

  - [ ] Lint to detect code block contents without "base indentation" in docs.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15024.

  - [ ] Lint to detect extra "base indentation" in Rust code blocks.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15025.

  - [ ] Lint to detect inconsistent "style" for safety-related docs/comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15033.
    + Related: https://github.com/rust-lang/rust-clippy/issues/15034.
    + Example: https://lore.kernel.org/rust-for-linux/4823a58093c6dfa20df62b5c18da613621b9716e.1749554599.git.viresh.kumar@linaro.org/.

  - [ ] Lint to detect `//` within `///` (only when the empty comment is empty).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15245.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15260.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72nh71s9to5v1KHJWN79bEFv97zN6jcGJyEQkaJZ5UuJfg@mail.gmail.com/.

  - [ ] Lint to disallow imports of certain items (to force users to write e.g. `ordering::Any`).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15244.
    + Lore: "[PATCH v6 3/9] rust: sync: atomic: Add ordering annotation types".

  - [ ] `wildcard_imports`'s `allowed-wildcard-imports` with several path segments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15246.

  - [ ] `manual_is_multiple_of` suggests change that could alter behaviour.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15335.

  - [ ] Providing information about integer type aliases with multiple sizes.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15337.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72ktx9JsTXN_HTfjGWHxpBh430tkxHE2xL_1BQB2yb16rA@mail.gmail.com/.

### Low priority (we will likely not use them in the end)

  - [ ] Conditional compilation for `clippy.toml`?
    + No concrete use cases from our side yet; and if needed, we could always handle it on our side generating `.clippy.toml` on the fly (and using `CLIPPY_CONF_DIR` to find it in the `objtree` instead of the `srctree`).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11433.

  - [ ] Fine-grained `check-private-items` (https://doc.rust-lang.org/clippy/lint_configuration.html#check-private-items).
    + So far, we have `check-private-items` enabled, but we do not have all the lints covered enabled, and in the future we might want to enable them, thus `check-private-items` may make it harder to start.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13074.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Overindented lines lint (similar to `doc_lazy_continuation`).
    + We had a case in https://lore.kernel.org/rust-for-linux/ZxkcU5yTFCagg_lX@ohnotp/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13601.
    + PR: https://github.com/rust-lang/rust-clippy/pull/13711 (1.86).

  - [x] Support/document running Clippy as a `rustc` wrapper.
    + PR: https://github.com/rust-lang/rust-clippy/pull/6782.

  - [x] Configuring lint levels when using `clippy-driver`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/6799.

  - [x] Normalize semicolon inside/outside blocks for `()` returning expressions (`semicolon_outside_block` and `semicolon_inside_block`, 1.68.0).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/7322.
    + PR: https://github.com/rust-lang/rust-clippy/pull/9826.

  - [x] Lint to warn about missing `// SAFETY:` explanations (`undocumented_unsafe_blocks`, 1.58.0).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/9330.
    + PR: https://github.com/rust-lang/rust-clippy/pull/7748.

  - [x] Lint to warn about unexpected `# Safety` contracts (i.e. the reverse of the `missing_safety_doc` lint) (`unnecessary_safety_doc`, 1.67.0).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/6880.
    + PR: https://github.com/rust-lang/rust-clippy/pull/9822.

  - [x] Lint to warn about unexpected `// SAFETY: ` comments (i.e. the reverse of the `undocumented_unsafe_blocks` lint) (`unnecessary_safety_comment`, 1.67.0).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/7954.
    + PR: https://github.com/rust-lang/rust-clippy/pull/9851.
    + Unclear if we will use `// SAFETY: ` comments also for explaining why safe code makes other unsafe code sound, though.

  - [x] Lint to catch `#[no_mangle]` but non-`extern "C"` (`no_mangle_with_rust_abi`, 1.69.0).
    + From: https://github.com/Rust-for-Linux/linux/pull/967.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/10347.
    + PR: https://github.com/rust-lang/rust-clippy/pull/10369.

  - [x] Lint to catch printing/formatting pointers (including `:p` and `:?`).
    + In Linux, ideally, there would be a way to customize all pointer printing, i.e. including `:p` and `:?`, so that we can get them hashed as expected, and thus at that point we wouldn't need to lint for it. Meanwhile, this lint can be useful (and may be for other projects that do not want any printing whatsoever, too).
    + PR: https://github.com/rust-lang/rust-clippy/pull/14792 (1.89).
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/channel/288089-General/topic/Clippy.20lint.20for.20detecting.20pointer.20printing/near/517813625.

  - [x] Macros wrapping expressions in `unsafe` blocks when using `unsafe_op_in_unsafe_fn`.
    + This was eventually handled by `clippy::macro_metavars_in_unsafe`, which is in `suspicious` already, so we are already using it and e.g. writing a "bad" `container_of!` (and using it) does lint for us.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/7323.
    + Unfinished PR: https://github.com/rust-lang/rust-clippy/pull/7469.
    + PR: https://github.com/rust-lang/rust-clippy/pull/12107 (1.80).

  - [x] Lint to suggest `cast_signed` and `cast_unsigned` (added suggestion to `cast_possible_wrap` and `cast_sign_loss`).
    + Stable since Rust 1.87, unstable since 1.80 (i.e. we would need to wait until we bump the minimum).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14974.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15384 (1.92).

---

### Required (we almost certainly want them)

  - [ ] `disallowed_macros` false negatives.
    + For `dbg_macro` emulation purposes.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11431.
    + PR (for the `$t + $t` case): https://github.com/rust-lang/rust-clippy/pull/11439 (1.74).

  - [ ] `cast_lossless` false negative on `char as u32`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14469.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14470.
    + Lore: https://lore.kernel.org/rust-for-linux/D8PAQXHJDVQE.36QKQGBVVL4QU@proton.me/.

### Nice to have (probably not critical, we could workaround if needed, etc.)

  - [ ] `unnecessary_safety_comment` does not lint for "orphan" comments.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14556.

  - [ ] `unnecessary_safety_comment` inconsistency with wrong-style safety section.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15034.

  - [ ] Feedback on `needless_continue` in Rust 1.86.0 (which we will probably disable globally).
    + Lore: https://lore.kernel.org/rust-for-linux/20250401221205.52381-1-ojeda@kernel.org/.
    + Lore: https://lore.kernel.org/rust-for-linux/20250403163805.67770-1-ojeda@kernel.org/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14536.

  - [ ] Less false positives in `clippy::incompatible_msrv`.
    + We ended up allowing globally `clippy::incompatible_msrv` early 2026 for Linux v7.1, but it could be nice to eventually use it again (possibly when no more language unstable features remain and/or when the false positives are low enough, since it can be fairly confusing to developers).
    + Lore (patch that globally enabled the lint): https://lore.kernel.org/rust-for-linux/20260405235309.418950-8-ojeda@kernel.org/.
    + Lore (note on false positives): https://lore.kernel.org/rust-for-linux/CANiq72mJTT7xFnhm-CeOZM_3ZwGdaQ8F2zUbONpPbqJ8g7DokQ@mail.gmail.com/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14827.
      * We currently do not use `cfg(version = "...")` but instead our own Kconfig `--cfg` gates (see "Numerical comparisons in conditional compilation" in https://github.com/Rust-for-Linux/linux/issues/354).

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] `README`: document that Clippy may change codegen.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/8035.
    + PR: https://github.com/rust-lang/rust-clippy/pull/8037 (1.60).

  - [x] `new_ret_no_self` false positive when returning `impl Trait<Self>`.
    + For `pin-init` usage.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/7344.
    + PR: https://github.com/rust-lang/rust-clippy/pull/9733 (1.67).

  - [x] `macro_metavars_in_unsafe` false negative without statement.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13219.
    + PR: https://github.com/rust-lang/rust-clippy/pull/13220 (1.82?).

  - [x] `single_match` difference in 1.85.0 -- is it intended?
    + We cannot use `expect` in https://lore.kernel.org/rust-for-linux/20250122054719.595878-1-dirk.behme@de.bosch.com/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14418.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14420 (1.87?).

  - [x] Diagnostic for unexpected paths in configuration file.
    + For instance, for `disallowed_macros`'s paths.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/11432.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14397 (1.87?).

  - [x] Reduce or split `ptr_eq`.
    + One "major addition" to the lint (linting all pointer comparisons) added in 1.87.
    + We may need to `allow` it globally otherwise, like `needless_continue`.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14536.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14525.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14526.
    + Backport PR (for Rust 1.87): https://github.com/rust-lang/rust/pull/140810, https://github.com/rust-lang/rust/pull/140859.
    + Patch that `allow`ed a few of them (when applied): https://lore.kernel.org/rust-for-linux/20250502140237.1659624-3-ojeda@kernel.org/.

  - [x] `undocumented_unsafe_blocks` false positives around attributes.
    + Workaround: moving the attribute on top always fixes it.
    + Workaround: where it makes sense, moving the comment inside the expression, also works.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13189.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15213 (1.90).

  - [x] Fix false positives around `undocumented_unsafe_blocks`'s `accept-comment-above-statement`.
    + i.e. that trigger when long statements are split into several lines by e.g. `rustfmt`.
    + Originally Clippy didn't support the config option, but eventually it was implemented and then made the default later on. However, there have been false positives around it.
    + When we introduced the lint in Linux (commit db4f72c904cb ("rust: enable `clippy::undocumented_unsafe_blocks` lint")), we just put the `// SAFETY` comment on the previous line, even if it is in the middle of the statement, to workaround it, e.g. see `do_unlocked` in the commit.
    + Starting with Rust 1.87.0, false positives like those we triggered in the kernel seem to be fixed, e.g. https://lore.kernel.org/rust-for-linux/87msbw1s9e.fsf@kernel.org/ and https://lore.kernel.org/rust-for-linux/DBG25OQZJ18V.1W13FEOPX8MOH@kernel.org/.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13024.
    + PR: https://github.com/rust-lang/rust-clippy/pull/13888 (1.87).

  - [x] Avoid `clippy::incompatible_msrv` for features enabled.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14425.
    + PR: https://github.com/rust-lang/rust-clippy/pull/14433 (1.90).
    + Lore: https://lore.kernel.org/rust-for-linux/ffd14e81-c64e-42fa-aa18-60c8036f13e8@sirena.org.uk/.

  - [x] `unnecessary_safety_comment` does not lint for the first line.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14553.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15354 (1.91).

  - [x] `unnecessary_safety_comment` does not lint the first item of a module without a body.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14554.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15354 (1.91).
    + Lore: https://lore.kernel.org/rust-for-linux/20250405060154.1550858-3-andrewjballance@gmail.com/.

  - [x] `unnecessary_safety_comment` does not lint for a `doc(hidden)` item.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14555.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15678 (1.92).

  - [x] `declare_interior_mutable_const` fires for static pointer types (`warning: a `const` item should not be interior mutable`).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/13233.
    + PR: https://github.com/rust-lang/rust-clippy/pull/13207 (1.89).
    + PR: https://github.com/rust-lang/rust-clippy/pull/13290 (1.82).
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/channel/291565-Help/topic/lock.20class.20key.20in.20const.20triggers.20interior.20mutable.20const.20warn/near/572171104.

  - [x] `clippy::double_parens` false positive.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/15852.
    + PR: https://github.com/rust-lang/rust-clippy/pull/15939.
    + PR: https://github.com/rust-lang/rust/pull/149656 (1.92).
    + Lore: https://lore.kernel.org/rust-for-linux/DGUA6UMYDGG9.1AA0FD146PS3K@garyguo.net/.

  - [x] `clippy::precedence` "false positives" (with respect to later versions).
    + Issue: https://github.com/rust-lang/rust-clippy/issues/14097 (i.e. started in Rust 1.85.0).
    + PR: https://github.com/rust-lang/rust-clippy/pull/14115 (1.86.0).

**Comment by tgross35** [comment]
I am working on enabling some of these. I will exclude `unnecessary_safety_comment` for now because it has a false positive in macros https://github.com/rust-lang/rust-clippy/issues/10084
