### ISSUE TITLE
`rustdoc` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#350]
Note: there is the "A-rust-for-linux" label in the `rust` repository: https://github.com/rust-lang/rust/labels/A-rust-for-linux.

Please see as well documentation-related lints at https://github.com/Rust-for-Linux/linux/issues/349 (i.e. some may make sense in Clippy, some in `rustdoc`).

### Required (we almost certainly want them)

  - [ ] External references map file.
    + The idea is to be able to write intra-doc-like links that point to external resources, e.g.:

      ```rust
      /// Uses the kernel's C [`struct mutex`].
      ```

      where the URL is automatically provided, e.g. to some C documentation. Similarly, it could be use to avoid duplicating URLs that need to be manually updated, e.g. like a BibTeX database file. For instance, references to external articles, page/webs, papers, Wikipedia entries, etc.

      To define those links, `rustdoc` could be given a "external references" file containing a map of (term, URL) pairs (e.g. in a JSON or Markdown-references-like file with one reference per line), possibly passed via the CLI, e.g.:

      ```sh
      --external-references-file books.json
      ```

      That way, the user is the one that defines the links and terms, possibly exporting them from other tooling (such as a documentation tool for another programming language).

      Multiple files could also be allowed -- having different files for different topics/categories of references may be useful/cleaner for users.

      An interesting extension could be to allow references to contain extra metadata (i.e. not just the URL), like in BibTeX. `rustdoc` could then potentially render that metadata somehow, like Wikipedia's references (e.g. when clicking them, or when clicking a small information button close to the link, or as a footnote, or on hover...). Another possibility is that, even without any extra metadata, `rustdoc` could also decide to render them differently than "normal links".

      There is potential for ambiguity with existing links. Possibly a syntax could be provided to disambiguate (whether required in all cases or just in cases of ambiguity), as suggested by @aDotInTheVoid, e.g.:

      ```rust
      /// Uses the kernel's [extern@`struct mutex`].
      ```

      Currently (Rust 1.78), when one uses an intra-doc link that matches a Markdown one (i.e. the intra-doc link title is the same as the Markdown link label of a link reference definition), `rustdoc` renders it as the Markdown link, rather than the intra-doc link, without warning, e.g.:

      ```rust
      /// This ambiguous link ([`ThisModule`]) goes to the website, not to the Rust item.
      ///
      /// [`ThisModule`]: https://rust-for-linux.com
      ```

      An alternative could have been to use:

      ```sh
      --markdown-after-content references.md
      ```

      with a `references.md` file with:

      ```md
      [Wikipedia]: https://www.wikipedia.org
      ```

      but currently (Rust 1.78) those references cannot be used from elsewhere. Instead, a potential `--markdown-after-every-item` could work.

      Similarly, including the references via `include_str!` as suggested by @jyn514 works, e.g.:

      ```rust
      /// Here are all the docs, with [Wikipedia] links.
      ///
      #[doc = include_str!("references.md")]
      ```

      but requires doing so in each case/item (rather than globally).

    + Status: Idea seemed reasonable to maintainers, RFC to be written.
    + Cc: @aDotInTheVoid, @GuillaumeGomez, @jyn514.

  - [ ] `rustdoc` lint to flag potential intra-doc links.
    + Issue: https://github.com/rust-lang/rust/issues/131510.

  - [ ] Documentation under conditional compilation.
    + The kernel has a lot of configuration options and it would be useful to have a way to generate the docs independently of the particular kernel configuration.
    + A partial workaround is having an `allyesconfig` configuration (or similar) generated for each architecture.
    + Issue: https://github.com/rust-lang/rust/issues/1998.
    + Issue: https://github.com/rust-lang-nursery/portability-wg/issues/8.

  - [ ] Custom logo/favicon flag (for local/bundled image files).
    + RFC: https://github.com/rust-lang/rfcs/pull/3226.
    + Alternative via another RFC (https://github.com/rust-lang/rfcs/pull/3397): https://github.com/rust-lang/rfcs/pull/3226#issuecomment-2018112367.
    + The workaround broke once in 1.76 (https://github.com/rust-lang/rfcs/pull/3226#issuecomment-2017918708).

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] Collapsed-by-default (or switch) for uncommon/advanced APIs.
    + As a potential way to reduce the burden for most readers/users of `alloc` if fallible allocations were to be added (`try_*`).

  - [ ] Check hidden/private items.
    + Issue: https://github.com/rust-lang/rust/issues/149105.
    + For instance to detect broken intra-doc links.
    + This can be worked around by doing two passes (i.e. one for checking, and one for the actual generation).
    + A superset feature is the "Runtime toggle for private/hidden items documentation (and `/* private fields */`)".
    + This was temporarily the case due to https://github.com/rust-lang/rust/pull/147153#issuecomment-3395484636 (1.92), but it wasn't intentional, and thus it got fixed in https://github.com/rust-lang/rust/pull/147809 (1.92).
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72k8KmpFyKAFZ293GDUWx5=HJtksR02hTU8-H9PX7xsT+g@mail.gmail.com/

  - [ ] Runtime toggle for private/hidden items documentation (and `/* private fields */`).
    + Issue: https://github.com/rust-lang/rust/issues/149106.
    + i.e. like `--document-private-items` and `--document-hidden-items`, but at runtime.
    + Rather than having to render the docs twice and then providing a custom UI to the user to switch between the two.
    + PR: https://github.com/rust-lang/rust/pull/141299.
    + Cc: @lolbinarycat.

  - [ ] Private documentation (perhaps as an extension of the private items/fields toggle).
    + See https://github.com/rust-lang/rust/pull/141299#issuecomment-2895118973.

      > Before I forget, "one more thing" that is probably out of scope but related to this toggle: we could consider having a way to write "private documentation", e.g. in the Linux kernel we sometimes have private invariants that we put currently in the documentation in their own section (`# ...`), but are really an implementation detail that ideally would go in a "private section of the docs". Using normal comments means we lose some features (e.g. nice rendered docs, intra-doc links, etc.), sadly. If we had that, this toggle could also show/hide that.

  - [ ] `rustdoc --emit=dep-info=...`.
    + We may want to start using it in the kernel eventually to properly track dependencies and avoid regenerating docs every time (currently we have to also clean up completely the output folder to avoid issues when users may have switched the Rust version, i.e. when incompatible output files may be present from previous generations).
    + Issue: https://github.com/rust-lang/rust/issues/91982.
    + Status: stabilization PR (https://github.com/rust-lang/rust/pull/146220). Added as unstable in 1.87 (https://github.com/rust-lang/rust/pull/137684). Note that `--emit` in general was added way earlier, in 1.53 (https://github.com/rust-lang/rust/pull/83478).
    + PR: https://github.com/rust-lang/rust/pull/137684 (1.87).
    + PR: https://github.com/rust-lang/rust/pull/146220.

  - [ ] `doc_cfg`, `auto_doc_cfg`, `cfg_hide`.
    + PR: https://github.com/rust-lang/rust/pull/100883.
    + RFC: https://github.com/rust-lang/rfcs/pull/3631.
    + Cc: @GuillaumeGomez.

  - [ ] External `doc(cfg(...))` map file (customization in general of the rendered banner).
    + Issue: https://github.com/rust-lang/rust/issues/87139.

  - [ ] Add copy button for code blocks.
    + Issue: https://github.com/rust-lang/rust/issues/86851.

  - [ ] Add "expand" button for code blocks to show hidden parts.
    + An alternative is just looking at the "Source" button.
    + PR: https://github.com/rust-lang/rust/pull/86892.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72=_KAgUZ9u5YY-iw7kyA9R1Nv6eNzZqMLSwOLQk6sR7kw@mail.gmail.com/.

  - [ ] Being able to use intra-doc links in "normal" comments.
    + In documentation, we write things like:

      ```rust
      /// See [`SomeType`].
      fn f() {
          // ...
      }
      ```

      The idea is to be able to write the same in normal comments:

      ```rust
      // See [`SomeType`].
      ```

      This includes things like `// SAFETY` comments, which tend to refer to types and functions/methods, e.g.:

      ```rust
      // SAFETY: This pointer comes from `Arc::into_raw` and we've been given back ownership.
      let boxed = unsafe { KBox::from_raw(ptr) };
      ```

      ```rust
      // SAFETY: It is safe to send `Arc<T>` to another thread when the underlying `T` is `Sync` ...
      unsafe impl<T: ?Sized + Sync + Send> Send for Arc<T> {}
      ```

    + The potential advantages would be that:
      
        * `rustdoc` could give an error if the link does not exist, just like it does for the documentation, so preventing typos and missing changes in refactors etc. We had several such cases, e.g. https://lore.kernel.org/rust-for-linux/c2becbdf-1258-4a33-9fa9-3b63b53ad099@kernel.org/

        * `rustdoc` (and IDE tooling) could provide clickable links for those in the source view.

        * It would be more consistent with normal docs, which simplifies e.g. copy-pasting from one to the other.

  - [ ] Tagging doctests.
    + Sometimes we need to have "custom environments" for certain doctests. For instance, in order to avoid repetition to prefix certain code.
    + Having a way to "tag" doctests and have `rustdoc` give those tags in the JSON would perhaps allow us to implement those features on our side on the generator.
    + `rustdoc` already provides an `unknown` field with the doctests attributes it doesn't recognize in the `--output-format=doctest` feature we requested, but it may be a good idea to have an agreed upon way or namespace to have custom tags to avoid collisions, e.g.

      ```
      /// ```tag:foo,tag:bar
      ```

    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72nLzuCXh0r5W0HMM36f9yTSQfP9yCxXbzH+wS7VxFM2Eg@mail.gmail.com/.

### Low priority (we will likely not use them in the end)

  - [ ] Strip blank lines on both the top and the bottom sides.
    + Issue: https://github.com/rust-lang/rust/issues/78695.
    + Would also fix https://github.com/rust-lang/rust/issues/102996.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Jump to definition (i.e. links in source view, `--generate-link-to-definition`).
    + Moved to main list since we started using it.

  - [x] `rustdoc @argfile`.
    + PR: https://github.com/rust-lang/rust/pull/82261 (1.52).

---

### Nice to have (probably not critical, we could workaround if needed, etc.)

  - [ ] Using `super` in doctests errors.
    + Issue: https://github.com/rust-lang/rust/issues/130274.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/stream/291565-Help/topic/Cargo.20expand.20on.20kunit.20test/near/469662954.

### Low priority (we will likely not use them in the end)

  - [ ] Inconsistent number of blank lines rendered top/bottom.
    + Issue: https://github.com/rust-lang/rust/issues/102996.

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Avoid requiring an absolute path for the target spec file.
    + PR: https://github.com/rust-lang/rust/pull/85361.

  - [x] `broken_intra_doc_links` behavior change with `macro_rules` not in scope since 1.63.
    + Issue: https://github.com/rust-lang/rust/issues/106142.
    + Issue: https://github.com/rust-lang/rust/issues/110879.
    + PR: https://github.com/rust-lang/rust/pull/110881.
    + It turns out the new behavior is intended, and the fact that the links still got generated was just a compatibility measure for docs.rs, which will go away in Rust 1.71.

  - [x] ICE: `rustdoc`'s `--test` option may call `rustc` with too many arguments.
    + Issue: https://github.com/rust-lang/rust/issues/122722.
    + PR: https://github.com/rust-lang/rust/pull/122840 (1.79).

  - [x] ICE documenting `compiler_builtins.rs` with `--remap-path-prefix`.
    + Our workaround is to skip the flag only for `rustdoc`.
    + Issue: https://github.com/rust-lang/rust/issues/138520.
    + PR: https://github.com/rust-lang/rust/pull/138556 (1.87).
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72ntZj10H1DBqRyX=uLertMw59e=PM7ESVJ0zWfu_ECnnA@mail.gmail.com/.
    + Patch: https://lore.kernel.org/rust-for-linux/20250314213333.2230670-1-ojeda@kernel.org/.

  - [x] `rustdoc` does not handle target modifiers properly.
    + Issue: https://github.com/rust-lang/rust/issues/144521.
    + PR: https://github.com/rust-lang/rust/pull/144523 (1.90).
    + Lore: https://lore.kernel.org/rust-for-linux/36cdc798-524f-4910-8b77-d7b9fac08d77@oss.qualcomm.com/.
    + Lore (workaround patch): https://lore.kernel.org/rust-for-linux/20250727092317.2930617-1-ojeda@kernel.org/.

  - [x] `rustdoc` `--test` (doctests) also does not handle target modifiers properly.
    + Issue: https://github.com/rust-lang/rust/issues/146465.
    + PR: https://github.com/rust-lang/rust/pull/148068 (1.93).
    + Backport PR: https://github.com/rust-lang/rust/pull/149572 (1.92).
    + Lore (workaround patch): https://lore.kernel.org/rust-for-linux/20251102212853.1505384-2-ojeda@kernel.org/.
    + See the previous related issue "`rustdoc` does not handle target modifiers properly" below as well.
    + Another compounding bug (https://github.com/rust-lang/rust/pull/148068#issuecomment-3478399881), was fixed in 1.92.0 in the meantime, possibly by https://github.com/rust-lang/rust/pull/147292 (1.92).

  - [x] `rustdoc`: make `--emit` and `--out-dir` mimic `rustc`.
    + PR: https://github.com/rust-lang/rust/pull/153003 (1.96).

  - [x] "error: target feature `fp-armv8` cannot be toggled with `#[target_feature]`: Rust ties `fp-armv8` to `neon".
    + Issue: https://github.com/rust-lang/rust/issues/137366 (introduced in 1.85.0).
    + PR: https://github.com/rust-lang/rust/pull/137632 (1.85.1).
    + Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1135220.

**Comment by lolbinarycat** [comment]
> Idea seemed reasonable to maintainers, RFC to be written.

Any progress on that? I've been working on rustdoc, and recently I've been cleaning up a few things in the intra-doc link system.

**Comment by ojeda** [comment]
Not yet -- I will eventually get to it, since we are definitely interested in it. I have had a few more ideas around it. If you have time to put into it, please let me now!

**Comment by lolbinarycat** [comment]
I have plenty of time, the limitation is actually if t-rustdoc has enough time to review the contributions!

being able to say "rust4linux wants it" would probably help a fair bit towards getting it prioritized, though.

**Comment by ojeda** [comment]
That makes sense, yeah.

If you have a lot of time, and want to work on the feature, then please go ahead (and thanks a lot!), it will be a while until I can put time into that due to other priorities. I am happy to help or co-author or something like that. If what you want is write code rather than the RFC, then I think for a feature like that having a prototype implementation could also help.

Please feel free to contact me by email or in the Rust or Rust for Linux Zulips.
