### ISSUE TITLE
`bindgen` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#353]
Note: see as well the "rust-for-linux" label in `bindgen`: https://github.com/rust-lang/rust-bindgen/labels/rust-for-linux.

### Required (we almost certainly want them)

  - [ ] Support for a GCC-based backend.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/1949.
    + Related: https://github.com/rust-lang/rust-bindgen/issues/2962.

  - [ ] Support non-trivial object-like macros that evaluate to a numeric value when fully expanded.
    + For instance:
      * An expression, e.g. `#define A ((int)1)`.
      * Macros using function-like macros, e.g. Linux ioctl `#define`s using `_IO*`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/316 (expressions).
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/753 (using other macros).
    + PR ("one pass per macro", i.e. option 1 below): https://github.com/rust-lang/rust-bindgen/pull/2779 (0.70.0).
    + PR (follow up fixes): https://github.com/rust-lang/rust-bindgen/pull/2823 (0.70.0?).
    + Lore (trying out `--clang-macro-fallback`, kernel patch with workarounds to test `bindgen` available): https://lore.kernel.org/rust-for-linux/CANiq72m20pom+B9EmWO+91E8fjbMEob3JmvHRQ6UaXe_JmatfA@mail.gmail.com/.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3069.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3070.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3071.
    + Issue (on `--clang-macro-fallback`'s types): https://github.com/rust-lang/rust-bindgen/issues/3200.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3072.
    + Related PR: https://github.com/rust-lang/rust-bindgen/pull/3111.
    + Meta-issue: https://github.com/rust-lang/rust-bindgen/issues/2426.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/bindgen.20issue.20.23753.20-.20function.20like.20macros/near/420514477.
    + Cc: @jbaublitz who has been following/helping with this issue since the beginning and potentially interested in working on it.
    + Status:
      > I met with @emilio a few days ago (early February 2024), and we discussed this for a bit, including the `bindgen`-side solution/workaround of emitting extra code so that we can fetch the value.
      >
      > The variations we discussed were "one pass per macro" (slow, but could work without user input), "one extra pass for all macros" (this would be fast, but would require the user to pass e.g. a regex of matching macros to evaluate that are "known to be constants" already); as well as the possibility of "appending the macros later on" (i.e. add them into a context or similar, which may be possible or not with the current API; we should also check e.g. what [Clang-Repl](https://clang.llvm.org/docs/ClangRepl.html)/Cling does here).
      >
      > So, in summary, `bindgen` would be happy with a workaround. But solving it in LLVM is, of course, the best long-term, so that would be great too (ideally both, so that we can use the feature before projects like the kernel have a minimum LLVM version >= 19).
      >
      > For the LLVM side, @AaronBallman (the Clang maintainer) told me he would be happy to review our changes if we sent them, in order to help `bindgen`, so that is great if someone wants to work on it.
      * The first option, i.e. "one pass per macro" was [prototyped by @jbaublitz](https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/bindgen.20issue.20.23753.20-.20function.20like.20macros/near/425001619).

  - [ ] Support aligned members (including structs with bitfields) inside packed structs.
    + Workaround: mark the type as opaque, and if needed, access it in another way (e.g. from C).
    + See as well the Rust support for it: https://github.com/Rust-for-Linux/linux/issues/354.
    + i.e. avoid generating `#[repr(C, align(...)]` inside an `#[repr(C, packed)]`.
    + Seen for `struct alt_instr`: https://lore.kernel.org/all/202212272003.rgQDX8DQ-lkp@intel.com/
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2179.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/867.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2725.
    + Related issue: https://github.com/rust-lang/rust-bindgen/issues/1538.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2388.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2734.
    + PR (RFC alternative 1): https://github.com/rust-lang/rust-bindgen/pull/2769.
    + PR (RFC alternative 2): https://github.com/rust-lang/rust-bindgen/pull/2770.
    + RFC: https://github.com/rust-lang/rfcs/pull/3806.

  - [ ] Support a new "enum variant" kind, similar to `rustified_enum`, that provides a safe method to transform a C enum to Rust.
    + The goal is to ensure at compile-time that, if the C side enum adds a variant, the Rust side (i.e. the conversion method) will be updated properly too.
    + From: https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/Enum.20handling/near/392620696.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2646.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2908.
    + Issue (revamping the CLI interface for `enum`s, from https://github.com/rust-lang/rust-bindgen/pull/2908#issuecomment-2528709843): https://github.com/rust-lang/rust-bindgen/issues/3050.
    + Issue (modifying existing behavior?): https://github.com/rust-lang/rust-bindgen/issues/3051.

  - [ ] `--with-derive-custom-struct` doesn't apply to `__BindgenBitfieldUnit`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3196.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/channel/291565/topic/Zeroable.20trait.20for.20C.20structs/near/509711564.
    + Rust for Linux branch with use case: https://github.com/y86-dev/linux/commits/bindgen-zeroable/.
    + Cc: @y86-dev.

  - [ ] Support passing attributes on the command line to add `#[zerocopy(on_error = skip)]`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3343.
    + `zerocopy` issue: https://github.com/google/zerocopy/issues/1769.
    + `zerocopy` PR (implements `#[zerocopy(on_error = skip)]`): https://github.com/google/zerocopy/pull/2982 (0.8.39).

  - [ ] A solution to convert headers with many groups of `#define` constants such as [`include/uapi/linux/input-event-codes.h`](https://github.com/Rust-for-Linux/linux/blob/v6.19/include/uapi/linux/input-event-codes.h).
    + The ideal solution would allow us to take headers like [`include/uapi/linux/input-event-codes.h`](https://github.com/Rust-for-Linux/linux/blob/v6.19/include/uapi/linux/input-event-codes.h) (that have many groups of `#define` constants, some with special values like `*_CNT`/`*_MAX`) and, with minimal modifications (perhaps in the form of comments), have them produce more idiomatic code (e.g. such as if each group was a proper `enum`).
      * If the modifications needed are extensive, then it may be that it is simpler to convert a header to use actual C `enum`s (which we did in the past).
      * However, that is not always possible, e.g. changing uAPI headers (like the one mentioned) may break C or C++ consumers that we don't control.
    + HackMD: https://hackmd.io/jDrRNEK7RpGBB5lxuEKyOA.
    + Cc: @0xIO32 @dakr.

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] `process_comments` via CLI.
    + See as well "C javadoc comments" below.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2953.

  - [ ] `bindgen` does not generate `union` + `ManuallyDrop` for some cases.
    + Even when `manually_drop` style is requested (e.g. via `--default-non-copy-union-style manually_drop` or `--manually-drop-union '.*'`).
    + This happens in the kernel via `union`s with only `DECLARE_FLEX_ARRAY` such as in [`struct bpf_array`](https://elixir.bootlin.com/linux/v6.14-rc2/source/include/linux/bpf.h#L1968-L1972).
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3130.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3348.
    + Rust for Linux issue: https://github.com/Rust-for-Linux/linux/issues/1137.
    + Related: https://github.com/Richardhongyu/rfl_empirical_tools/issues/1.

  - [ ] Translating inline assembly into Rust.
    + See "Querying GCC-style inline assembly so that `bindgen` can translate it into Rust inline assembly." in https://github.com/Rust-for-Linux/linux/issues/1132.
    + Cc: @dingxiangfei2009.

  - [ ] Translating function-like macros into Rust.
    + PR (`--translate-function-macros`): https://github.com/rust-lang/rust-bindgen/pull/3350.
      * It converts a subset of macros into `const fn`s with a single type for input/output parameters.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Support `unsafe_op_in_unsafe_fn`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2063.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2266.

  - [x] Support `_Noreturn`, `[[noreturn]]`, `__attribute__((noreturn))`
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2094.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2259.

  - [x] Support `typedef`s shadowing types e.g. `typedef struct T *T;`.
    + In other words, avoid conflating C name spaces.
    + Seen in the past e.g. for `maple_*node`s (https://github.com/Rust-for-Linux/linux/issues/795).
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2227.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2304.

  - [x] Take advantage of `feature(core_ffi_c)` and `feature(c_size_t)`.
    + This avoids having to manually specify `--ctypes-prefix core::ffi`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2231.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2267.

  - [x] A way to query the Clang version being used.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2138.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2140.

  - [x] Compile-time layout tests.
    + We are planning to run the layout tests as e.g. KUnit tests, but if they were compile-time ones, it would be simpler.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2786.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2787 (0.xx.x).

  - [x] Support `static inline` functions in headers (by generating a wrapper).
    + Currently we do it manually. `bindgen` currently (0.64.0) has experimental support via `--wrap-static-fns --experimental`.
    + Netdev would like it, e.g. `skbuff.h` has 300+ `static inline`s: https://lore.kernel.org/rust-for-linux/f28d6403-d042-4ffb-9872-044388d0f9d9@lunn.ch/ (also sub-thread at https://lore.kernel.org/rust-for-linux/CANiq72kD6HVrDTjQrTXDujyjA4Z5ELM6Nh8kFfVfNXrvpfU1wA@mail.gmail.com/).
    + Tracking (?) Issue: https://github.com/rust-lang/rust-bindgen/issues/2900.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/1090.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2335.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2420.
    + Stabilization PR: https://github.com/rust-lang/rust-bindgen/pull/2928.

  - [x] Raw pointer bitfield accessors.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2674.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2876.

  - [x] Rust for Linux in the `bindgen` CI.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2851.

  - [x] CI: update to v6.12-rc5.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2970.
    + Reported in the CI of PR: https://github.com/rust-lang/rust-bindgen/pull/2969.

  - [x] A way to specify a MSRV, instead of `--rust-target` (which only supports a subset of versions).
    + For instance, when we started using `--rust-target`, the kernel supported Rust 1.78.0+ and `bindgen` 0.65.1+, thus we picked `--rust-target 1.68`, since it is the maximum stable version supported by the `--rust-target` flag in `bindgen` 0.65.1 (and it is lower than our MSRV).
    + Lore: https://lore.kernel.org/rust-for-linux/20241123180323.255997-1-ojeda@kernel.org/.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/rust.20version.20on.20generated.20bindings/near/484087179.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2993.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3006.

  - [x] A way to specify an output Edition, e.g. `--rust-edition`.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3002.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3000.

  - [x] CI: update to v6.13-rc1.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3030.

  - [x] Support for Edition 2024.
    + Not important, since we can keep compiling the bindings in an older edition like 2021, but it would be nice to migrate everything to Edition 2024 eventually if it becomes available in Debian Trixie.
    + Edition 2021: https://github.com/rust-lang/rust-bindgen/issues/2998.
    + `unsafe extern` issue: https://github.com/rust-lang/rust-bindgen/issues/2901.
    + `unsafe extern` PR: https://github.com/rust-lang/rust-bindgen/pull/3015.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3012.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3013.

  - [x] CI: update to v6.14 (which also fixes the `soft-float` issue since bindgen uses stable).
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3188.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3189.

  - [x] CI: update to v6.15-rc4.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3201.

  - [x] CI: update to v6.16-rc1.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3225.

  - [x] CI: update to v6.17-rc2.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3271.

  - [x] CI: update to v6.18-rc3.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3309.

  - [x] Support `--with-attribute-custom-enum`.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2520.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2866 (0.71.0).

---

### Required (we almost certainly want them)

  - [ ] BindgenUnion can get incorrect alignment on i686.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2773.

  - [ ] Issues with integer types assigned to macros.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/923.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3323.

### Low priority (we will likely not use them in the end)

  - [ ] Wrong target when `--target` is not passed to `bindgen`.
    + In the Linux kernel we currently pass explicitly `--target` in all cases, thus we should not be affected.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3352.

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Fix the ``called `Result::unwrap()` on an `Err` value: FromBytesWithNulError { kind: InteriorNul(4) }`` issue (affects 0.66.0 and 0.66.1, fixed in 0.68.0, note that 0.67.x does not exist, patched in e.g. Debian).
    + Commit: 981ad93c89a3 ("rust: warn about `bindgen` versions 0.66.0 and 0.66.1").
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2566.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2567.

  - [x] Support `--version` without header (affects 0.69.0, fixed in 0.69.1, regressed in 0.71.0, fixed again in 0.71.1).
    + We currently workaround it with a dummy parameter.
    + Commit: 9e98db178370 ("rust: work around `bindgen` 0.69.0 issue").
    + Issue (0.69.0): https://github.com/rust-lang/rust-bindgen/issues/2677.
    + Issue (0.71.0): https://github.com/rust-lang/rust-bindgen/issues/3039.
    + Issue (probably related, 0.71.0): https://github.com/rust-lang/rust-bindgen/issues/3037.
    + PR: https://github.com/rust-lang/rust-bindgen/issues/2678 (0.69.1).
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3040 (0.71.1).

  - [x] C javadoc comments are not Markdown-escaped, triggering `rustdoc` warnings.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2057.

  - [x] Attribute `btf_type_tag` makes `const`ness of pointers disappear.
    + It will allow to undo the https://github.com/Rust-for-Linux/linux/commit/f6bb7cb63be627aa22e31f954aa14ecc53ba3283 workaround.
    + Should be fixed in 0.61.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2244.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2245.

  - [x] "Unable to find libclang" problems (https://github.com/Rust-for-Linux/linux/issues/934), possibly related to Clang 15.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2360.
    + PR (may or may not solve our issue): https://github.com/rust-lang/rust-bindgen/pull/2368.

  - [x] `--wrap-static-fns` generates code that `return`s a call to a `void` function.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2485.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2497.

  - [x] `--wrap-static-fns` generates `()` for empty parameter lists.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/2484.
    + Should be fixed in 0.65.1.

  - [x] Fix the support for linking `libclang` statically.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/stream/291565-Help/topic/Build.20errors/near/391197677.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/2644.

  - [x] Missing fields in nested class with LLVM 22.
    + This caused Intel's kernel test robot, which had 0.72.0 and used LLVM 22, to send a bunch of reports (see Zulip link below).
    + LLVM: https://github.com/llvm/llvm-project/pull/147835.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3264.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3275.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3277.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3278 (0.72.1).
    + Lore: https://lore.kernel.org/all/aTEi3KUUkPVGS3ix@xsang-OptiPlex-9020/.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/channel/291565-Help/topic/lkp.20build.20errors.20in.20master/near/561383868.

  - [x] Forward references to `enum` types end up generating the wrong type.
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3179.
    + Issue (duplicate): https://github.com/rust-lang/rust-bindgen/issues/3205.
    + Workaround patch: https://lore.kernel.org/rust-for-linux/20250325184309.97170-1-ojeda@kernel.org/.
    + Lore: https://lore.kernel.org/rust-for-linux/87tt7md1s6.fsf@kernel.org/.
    + PR: https://github.com/rust-lang/rust-bindgen/pull/3346 (0.73.0?).

### Not a bug (the report was not considered a bug)

  - [x] "Duplicated" variable (due to `struct_group`).
    + Issue: https://github.com/rust-lang/rust-bindgen/issues/3089.

**Comment by pvdrz** [comment]
Hi everyone!

I have opened some PRs on bindgen adding some features you needed:

- https://github.com/rust-lang/rust-bindgen/pull/2259
- https://github.com/rust-lang/rust-bindgen/pull/2266
- https://github.com/rust-lang/rust-bindgen/pull/2267

I'd be happy to hear if the PRs here actually provide what you need.

**Comment by alex** [comment]
These look spot on to me. Thanks for your efforts!

**Comment by ojeda** [comment]
Added links above, thanks a lot @pvdrz! :)

**Comment by dwlsalmeida** [comment]
@ojeda Hey Miguel, is there a workaround in place for this? 

```
Support function-like macros that use other macros and that evaluate to a numeric value when fully expanded (e.g. for Linux ioctl #defines using _IO*).
```

I am trying to write a v4l2 driver and one of the issues I found was that the pixel formats bindings are not generated by bindgen because the V4L2_PIX_FMT_* stuff is defined using the v4l2_fourcc macro

**Comment by ojeda** [comment]
For something like pixel formats that are stable (given they are in `uapi`, right?), I guess the easiest is re-implementing them on the Rust side, especially if you want to give them a proper type etc. anyway. Probably using a small temporary script to perform the bulk of the conversion.

Otherwise, if performance is not too much of a concern (even if cross-language LTO could reduce the cost at some point), one alternative is "executing" the macro at runtime by providing a C function that does it for the Rust side. In your case this one is likely not interesting because the important bits are the parameters to the macro, rather than the macro itself.

**Comment by bjorn3** [comment]
For the drm fourcc pixel format codes, the drm-fourcc crate has some code which fetches all `#define` from the header, generates a constant for each `#define` in a new header and then runs bindgen on the generated header: https://github.com/danielzfranklin/drm-fourcc-rs/blob/main/build.rs

**Comment by dwlsalmeida** [comment]
One question though, suppose I use the approach suggested by @bjorn3 

Do I commit the bindings I generate? Asking because apparently bindings_generated.rs is not part of the kernel per-se and is only generated during build time.

**Comment by bjorn3** [comment]
I think the bindings should be generated on the fly to ensure they stay up to date, just like bindings_generated.rs.

**Comment by dwlsalmeida** [comment]
well, in which case I suppose that the code to generate them (i.e. something similar to the code in the drm-fourcc crate) would have to be integrated into the kernel build system somehow?

**Comment by bjorn3** [comment]
Indeed. There is already infrastructure to run code written in rust. See for example scripts/generate_rust_target.rs.

**Comment by dwlsalmeida** [comment]
Makes sense, thanks for the pointers!

**Comment by ojeda** [comment]
It depends. If these constants are strictly stable (unlike many kernel APIs that you may see in `bindings_generated.rs`), you have the possibility to commit them, but in that case I would recommend writing directly in Rust what you need (rather than raw bindings that then you wrap). This is why I mentioned above the stability. You could also have a test to verify both sides match, though that could be a one-off thing.

If you go the generated route (which many times is the only way), then indeed, you could use a host program (it does not necessarily need to be written in Rust, but as @bjorn3 mentions, the support is there, so I would recommend it -- though currently you will only have the Rust standard library available, e.g. no `regex`). This approach has the drawback of adding complexity (the host program) and, depending on how you implement/parse the C header, you may introduce constraints on the C side. Another similar option is a proc macro, but that is slower (triggered every time you recompile the `kernel` crate, which would be unneeded -- you only need to do it once) and non-"pure" (in the "do not use the environment from a proc macro" sense). 

Another angle to think about is whether new constants will appear frequently or not.

**Comment by zRedShift** [comment]
rust-lang/rust-bindgen#3350 might be relevant

**Comment by ojeda** [comment]
Added to the list, thanks Ronen!

I left some quick feedback in the `--translate-function-macros` PR. I think the feature design would need some discussion, perhaps something like an RFC.

**Comment by jgabaut** [comment]
I don't really know if it's relevant but I got here from the mention of: [#3352](https://github.com/rust-lang/rust-bindgen/issues/3352)
> ### Low priority (we will likely not use them in the end)
> 
>     - [ ]  Wrong target when `--target` is not passed to `bindgen`.
>         
>         - In the Linux kernel we currently pass explicitly `--target` in all cases, thus we should not be affected. Issue: [`clang_macro_fallback` doesn't propagate implicit `--target` to fallback translation unit rust-lang/rust-bindgen#3352](https://github.com/rust-lang/rust-bindgen/issues/3352).

I am really not sure why I got here, but I also found this old issue still open which could be also relevant:
- https://github.com/rust-lang/rust-bindgen/issues/2159

I opened https://github.com/rust-lang/rust-bindgen/issues/3381 thinking it was due to a transitive dependency bump, but I think I should stop now since I feel I am getting out of my depth.

Edit: it's probably not relevant since this issue is explicitly for Linux.

**Comment by ojeda** [comment]
Thanks! I added https://github.com/rust-lang/rust-bindgen/issues/2159 to our aligned+pack entry here.

Yeah, this list is essentially for things that we need for the Linux kernel, including bugs that we hit.

I also replied to your issue on the `bindgen` side, since it would be nice to save an example to reproduce for the future, even if it may end up being a duplicate issue.
