### ISSUE TITLE
`rustc` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#355]
Note: there is the "A-rust-for-linux" label in the `rust` repository: https://github.com/rust-lang/rust/labels/A-rust-for-linux.

See as well:
  - Architecture support [open issues](https://github.com/Rust-for-Linux/linux/issues?q=state%3Aopen%20label%3A%22%E2%80%A2%20arch%22).

### Required (we almost certainly want them)

  - [ ] x86's `CONFIG_CPU_MITIGATIONS` (previously `CONFIG_SPECULATION_MITIGATIONS`).
    + In C compilers, they are enabled via flags, but they are missing in `rustc`.
    + Some may be able to be enabled via LLVM target features.
    + For instance:
        * `CONFIG_MITIGATION_RETPOLINE`: moved to the main list since it got implemented.
        * `CONFIG_MITIGATION_RETHUNK`: moved to the main list since it got implemented.
        * `CONFIG_MITIGATION_SLS`:
          * Clang's/GCC's `-mharden-sls=all`.
          * Passing the target features in the target specification file works, but we cannot use `-Ctarget-feature=` due to the warnings -- see https://github.com/rust-lang/rust/issues/116851.
          * Draft PR: https://github.com/rust-lang/rust/pull/136597.
          * MCP: https://github.com/rust-lang/compiler-team/issues/869.

  - [ ] Export (somehow) a list of all `noreturn` symbols.
    + `objtool` needs a list of functions that do not return.
    + Currently, we have a workaround with some heuristics: https://lore.kernel.org/rust-for-linux/20240725183325.122827-6-ojeda@kernel.org/
    + It would be ideal if `rustc` could emit somewhere (e.g. a file, via `--emit=noreturns`) a list of `noreturn` symbols. In particular, Peter suggests using a section: https://lore.kernel.org/rust-for-linux/20240806202217.GZ37996@noisy.programming.kicks-ass.net/
    + Gary proposed reading DWARF instead and wrote a quick Rust script for it via `object` and `gimli`, though DWARF would need to be available or generated on the fly just for that (and we cannot commit a fixed list since the kernel config may change and we support several Rust versions and so on): https://gist.github.com/nbdd0121/449692570622c2f46a29ad9f47c3379a.
    + Cc: @nbdd0121.

  - [ ] `-funsigned-char` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html#index-funsigned-char), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-funsigned-char)).
    + It could perhaps be a flag like `-Cunsigned-char`, or a "target modifier" instead, if those (RFC) come to fruition.
    + The kernel uses it (unconditionally) since commit 3bc753c06dd0 ("kbuild: treat char as always unsigned") (v6.2).
    + The kernel uses a custom FFI mapping (`kernel::ffi::` instead of `core::ffi::`) everywhere (i.e. for `bindgen`-generated code as well as manually written code), so we have a workaround for that part. However, things like `CStr`/`c""` still use `core::ffi::`'s definition, so it would still be nice to match it.
    + Tracking Issue: https://github.com/rust-lang/rust/issues/138446.
    + PR: https://github.com/rust-lang/rust/pull/138290.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Changing.20the.20types.20in.20.60core.3A.3Affi.60/near/470131005.
    + Lore: https://lore.kernel.org/rust-for-linux/20240928193632.063d62a6.gary@garyguo.net/.

  - [ ] `-mpreferred-stack-boundary` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-mpreferred-stack-boundary-1), Clang does not support it) / `-mstack-alignment` (GCC does not support it, [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mstack-alignment)).
    + Used by: x86_64 (`-mpreferred-stack-boundary=3`, `-mstack-alignment=8`).
    + Used by: x86 (`-mpreferred-stack-boundary=2`, `-mstack-alignment=4`).
    + Issue: https://github.com/rust-lang/rust/issues/128833.
    + Commit: d9b0cde91c60 ("x86-64, gcc: Use -mpreferred-stack-boundary=3 if supported").
    + Commit: d77698df39a5 ("x86/build: Specify stack alignment for clang").
    + Commit: 8f91869766c0 ("x86/build: Fix stack alignment for CLang").

  - [ ] `-mskip-rax-setup` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-mskip-rax-setup), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mskip-rax-setup)).
    + Used by: x86_64.
    + Commit: d9ee948d8220 ("x86/asm: Use -mskip-rax-setup if supported").

  - [ ] `rustc`'s equivalent to `-Wframe-larger-than`.
    + See Klint's https://github.com/Rust-for-Linux/klint/blob/trunk/doc/stack_size.md.
    + Clippy has a lint, but Klint is more accurate (Clippy's one works essentially summing the total of the local variables, before even register allocation; thus it has false positives).
    + It should probably be in `rustc`, upstream Rust open to have it in nightly (even before a way to configure lints in general, i.e. for the stack size in this case, is figured out): https://hackmd.io/4iWZvqBnTq2KUetjKf5X-A.
    + Matthew has a WIP: http://github.com/maurer/rust/tree/stack-check.
    + Cc: @nbdd0121 @maurer.
    + Aapo Alasuutari says:
      > Oxide Computer has been using some compiler build output's stack size data to check their kernel against stack overflow. Nightly feature `emit_stack_sizes`.
      >
      > @nbdd0121 you may also be interested in the PR where they introduced the check: https://github.com/oxidecomputer/hubris/pull/1890.
      >
      > One more PR on the Hubris code, adding support for calculating tail call stack sizes: https://github.com/oxidecomputer/hubris/pull/2005

  - [ ] KHWASAN support (kernel hardware-assisted AddressSanitizer, `-fsanitize=kernel-hwaddress`).
    + Tracking Issue (sanitizers in general): https://github.com/rust-lang/rust/issues/39699.
    + Tracking Issue (stabilizing sanitizers): https://github.com/rust-lang/rust/issues/123615.
    + Clang (HWASAN): https://clang.llvm.org/docs/HardwareAssistedAddressSanitizerDesign.html.
    + GCC: https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003dkernel-hwaddress.
    + PR: https://github.com/rust-lang/rust/pull/153049.
    + MCP: https://github.com/rust-lang/compiler-team/issues/975.

  - [ ] BTF generation.
    + There is an effort to support BTF for Rust with LTO by generating BTF directly instead of going through `pahole` -- see https://github.com/Rust-for-Linux/linux/issues/1132.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/BTF.20generation.20in.20rustc.3F/near/577913877.

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] Support overriding all flags on the command line (i.e. support multiple `--target`, `--sysroot`, `--edition`...).
    + Some flags, such as `--target`, `--sysroot` and `--edition`, can only be applied once: it is a hard error to supply them more than once.
    + Some projects would benefit from a way to allow to override them, or have had issues related to this behavior. For instance:
        * The Linux kernel allows users to pass "additional" flags as environment variables, rather than having to pass (again) the entire flag list (or having in the kernel side a way to manually filter previous flags). This came up for the Android build and was a problem.
        * Compiler Explorer allows users to pass flags, but it added a custom UI for toggling the edition, which in turn meant writing `--edition` was a hard error unless handled especially, which was eventually added.
    + If backwards compatibility is desired, then perhaps an opt-in flag could be added, e.g. `--allow-override=target,edition`.
    + Lore: https://lore.kernel.org/rust-for-linux/20241112184455.855133-1-ojeda@kernel.org/.
    + CE Issue: https://github.com/compiler-explorer/compiler-explorer/issues/5429.
    + CE Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3765.
    + CE PR: https://github.com/compiler-explorer/compiler-explorer/pull/6789.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/Support.20overriding.20all.20flags/near/486988024.
    + MCP: https://github.com/rust-lang/compiler-team/issues/731.

  - [ ] `-falign-jumps=1`, i.e. not aligned ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-falign-jumps), Clang does not support it).
    + Used by: x86_64.
    + Used by: x86_32 (`-falign-jumps=0`, only for a few CPUs).
    + Commit: be6cb02779ca ("x86: Align jump targets to 1-byte boundaries").
    + Issue: https://github.com/rust-lang/rust/issues/128831.
    + This is not critical now, since we mainly support only `LLVM=1` builds so far, but eventually we will want to match the C side for GCC builds when those become non-experimental.

  - [ ] `-falign-loops=1`, i.e. not aligned ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-falign-loops), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-falign-loops)).
    + Used by: x86_64.
    + Used by: x86_32 (`-falign-loops=0`, only for a few CPUs).
    + Issue: https://github.com/rust-lang/rust/issues/128832.
    + Commit: 52648e83c9a6 ("x86: Pack loops tightly as well").
    + For LLVM, we may use `-Cllvm-args=--align-loops=1`: https://github.com/rust-lang/rust/issues/128832#issuecomment-2526177829.

  - [ ] Showing type aliases (perhaps in addition to resolved types) in error messages, potentially manually tagging the cases with sometimes like `#[own_name]`.
    + From: https://github.com/Rust-for-Linux/linux/pull/990#discussion_r1151040011.
    + May allow us to have `Arc<T> = ARef<WithRef<T>>` and would improve readability of messages around e.g. `Mutex<T> = Lock<T, MutexBackend>`.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/type.20aliases.20and.20names.20in.20errors.

  - [ ] A way to skip the existing bypass of lints that come from foreign crates.
    + In our case, the "foreign" crates are really our own code, thus we would still want the lints.
    + In particular, this would allow to still get lints like `-Dunsafe_op_in_unsafe_fn` in generated code by proc macros.
    + PR that introduced the change: https://github.com/rust-lang/rust/pull/52467.
    + Related open issues: https://github.com/rust-lang/rust/issues/73556, https://github.com/rust-lang/rust/issues/53209.

  - [ ] `-masm=` equivalent (i.e. the ability to configure the assembly syntax default).
    + See https://github.com/Rust-for-Linux/linux/issues/354.

  - [ ] MSRV for  `rustc`, similar to Cargo's and Clippy ones (`--msrv=version`).
    + Issue & MCP: https://github.com/rust-lang/compiler-team/issues/772 (accepted).

  - [ ] Ability to load `.so` libraries under macOS.
    + Some kernel developers want to build Linux under macOS, but the kernel does not support that (the macOS support is maintained out-of-tree). So they may need something like this to minimize the differences with upstream. There may be other possible solutions (e.g. using symlinks, if that works, but it would require knowing the names in general). Perhaps this could help other projects to be ported to macOS too.
    + Issue: https://github.com/rust-lang/rust/issues/131720.
    + Lore: https://lore.kernel.org/rust-for-linux/CAJ-ks9==6mi7SF5rTR=YouwC6RwktJftqXHqhsBcHNTWxdbfig@mail.gmail.com/.

  - [ ] Flag output.
    + Issue (project-inline-asm): https://github.com/rust-lang/project-inline-asm/issues/14.
    + Cc: @fbq @nbdd0121.
 
  - [ ] Removing crate disambiguators from symbol names.
    + We plan to enforce that all crate names are unique in the kernel -- would that allow disambiguators to be removed from the generated symbol names?
    + Zulip: https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/Long.20symbols.20and.20crate.20disambiguators/near/501791872.

  - [ ] `dead_code` lint exceptions for more types.
    + Gary writes:
      > I wonder if it makes sense to request a feature to mute `dead_code` lint on
      > certain types which we know are there to represent a registration or resource
      > enablement.
      >
      > Currently rustc's dead_code lint has a builtin exception for `PhantomData`, but
      > I think a lot other types should have the same treatment, this can be useful
      > even for other core types, e.g `PhantomPinned`.
    + Lore: https://lore.kernel.org/rust-for-linux/DFVDAEMXT9LT.YCUH2BB8FV7C@garyguo.net/.
    + Cc: @nbdd0121.

### Low priority (we will likely not use them in the end)

  - [ ] `--check` mode / `--emit=check`.
    + Like `cargo check`, but for `rustc`.
    + `cargo check` appears to do `--emit=dep-info,metadata`, but that would not be needed for the leaves.
    + Currently, the best approximation appears to be `--emit=metadata`, but it would be nice to have a way that reduces the work to the minimum, at least avoiding to emit the metadata and temporaries.
    + `--emit=metadata=/dev/null` does not appear to work due to the generated temporaries (and `-Ztemps-dir` does not seem to change that).
    + Use case: some tests (e.g. in upstream Rust: the warning-free builds of `core` and `alloc` under `no_global_oom_handling` in `rustc`) and faster development (it could also be part of a dev-mode in the kernel, which could include other changes like disabling the missing documentation warning).
    + From: https://github.com/rust-lang/rust/pull/110652.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] `-Zpatchable-function-entry` support (GCC's and Clang's `-fpatchable-function-entry`), as well as the `patchable_function_entry` function attribute.
    + Moved into the main list since it got implemented.

  - [x] `-Zregparm=3` and `-Zreg-struct-return`.
    + Moved to the main list, since they got issued a tracking issue and are being implemented.
    + GCC's/Clang's `-mregparm=3` and `-freg-struct-return`.
    + Used by: x86 (i.e. 32-bit).
    + `-Zregparm=3` could have been just a bit of plumbing in `rustc`, but it turns out Clang is the one that has the logic to decide the registers, which then get marked in LLVM IR, and thus `rustc` needs to duplicate the logic (or moving it into LLVM and then wait for a release).
    + `-Zreg-struct-return` can be skipped if a `target.json` is used (`abi_return_struct_as_int` in target spec).
    + Tracking Issue: https://github.com/rust-lang/rust/issues/131749.
    + Tracking Issue: https://github.com/rust-lang/rust/issues/116973.
    + Issue: https://github.com/rust-lang/rust/issues/116972.
    + PR: https://github.com/rust-lang/rust/pull/130432.
    + PR: https://github.com/rust-lang/rust/pull/130777.
    + From: https://github.com/Rust-for-Linux/linux/pull/966#issuecomment-1429853966.
    + Commit: e852f3182f3e ("[PATCH] Add CONFIG for -mregparm=3") (in [`history.git`](https://git.kernel.org/pub/scm/linux/kernel/git/history/history.git/commit/?id=e852f3182f3ea)).
    + Commit: 25165120f243 ("[PATCH] x86: add -freg-struct-return to CFLAGS").

  - [x] Layout randomization.
    + `-Zrandomize-layout` (and `-Zlayout-seed=<seed>`) were implemented, though the use case of the MCP was debugging (e.g. detecting invalid layout assumptions), rather than security (which the kernel uses under some configurations -- see `CONFIG_RANDSTRUCT*`).
    + MCP: https://github.com/rust-lang/compiler-team/issues/457.
    + Feature Request: https://github.com/rust-lang/rust/issues/77316.
    + Issue: https://github.com/rust-lang/rust/issues/106764.
    + PR: https://github.com/rust-lang/rust/pull/87868.
    + PR: https://github.com/rust-lang/rust/pull/91932.

  - [x] CET (`-Zcf-protection=branch`).
    + Moved into the main list since it got implemented.

  - [x] KCFI (`-Zsanitizer=kcfi` & `-Zsanitizer-cfi-normalize-integers`).
    + Moved into the main list since it got implemented.

  - [x] x86's `CONFIG_X86_KERNEL_IBT` support (`-Zcf-protection=branch -Zno-jump-tables`).
    + GCC's/Clang's `-fcf-protection=branch -fno-jump-tables`.
    + Moved into the main list since the flags got implemented.

  - [x] Make `debug_triple` depend on `target.json` file content rather than file path.
    + Use case: https://github.com/Rust-for-Linux/linux/issues/792.
    + Related issue: https://github.com/rust-lang/rust/issues/92403.
    + PR: https://github.com/rust-lang/rust/pull/98225 (1.63).
    + Issue: https://bugs.launchpad.net/ubuntu/+source/rustc-1.62/+bug/2011355.

  - [x] Diagnostics for `-D` flags make it slightly harder to allow vs. `#![deny(...)]`.
    + Issue: https://github.com/rust-lang/rust/issues/114030.
    + PR (`help:` line): https://github.com/rust-lang/rust/pull/114089 (1.74).

  - [x] `.comment` section support.
    + PR: https://github.com/rust-lang/rust/pull/97550 (1.73).
    + PR (`rustc_codegen_gcc`): https://github.com/rust-lang/rust/pull/118068 (1.76).

  - [x] arm64: shadow call stack (SCS) support.
    + Used by: Kbuild (and, in particular, Android enables dynamic SCS).
    + Issue (support `-Zsanitizer=shadow-call-stack` in the builtin target): https://github.com/rust-lang/rust/issues/121972.
    + Issue (recognize `-Ctarget-feature=+reserve-x18` to avoid warning): https://github.com/rust-lang/rust/issues/121970.
    + PR (alternative 1: recognize `-Ctarget-feature=+reserve-x18` to avoid warning): https://github.com/rust-lang/rust/pull/124323.
    + PR (alternative 2: add a GCC/Clang-like `-Zfixed-x18` flag): https://github.com/rust-lang/rust/pull/124655 (1.80).
    + MCP: https://github.com/rust-lang/compiler-team/issues/748.
    + Issue (improve docs): https://github.com/rust-lang/rust/issues/121966.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/-ffixed-x18/near/430864291.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/New.20.60reserve-x18.60.20target.20feature/near/438370694.
    + Cc: @Darksonn.

  - [x] KASAN.
    + `-Zsanitizer=kernel-address` is being implemented.
    + PR: https://github.com/rust-lang/rust/pull/99679.

  - [x] `-fmin-function-alignment` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fmin-function-alignment_003dn), Clang does not support it) / `-falign-functions` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-falign-functions), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang1-falign-functions))
    + Moved into the main list since it got implemented.
    + Used by all architectures.
    + Used by: x86_32 (`-falign-functions=0`, only for a few CPUs).
    + The behavior wanted is that of GCC's `-fmin-function-alignment` and Clang's `-falign-functions`, i.e. align all functions, including cold functions.
    + There is [`feature(fn_align)`](https://github.com/rust-lang/rust/issues/82232), but we need to do it globally.
    + Issue: https://github.com/rust-lang/rust/issues/82232.
    + Original Issue: https://github.com/rust-lang/rust/issues/128830.
    + PR: https://github.com/rust-lang/rust/pull/134030 (1.86).

  - [x] `-Zsanitize-kcfi-arity` (i.e. the equivalent of Clang's [`-fsanitize-kcfi-arity`](https://clang.llvm.org/docs/ControlFlowIntegrity.html#fsanitize-kcfi-arity)).
    + Required for the upcoming `CONFIG_FINEIBT_BHI`.
    + Issue: https://github.com/rust-lang/rust/issues/138311.
    + Lore: https://lore.kernel.org/lkml/20250224123703.843199044@infradead.org/.
    + See as well https://github.com/Rust-for-Linux/linux/issues/1132.
    + PR: https://github.com/rust-lang/rust/pull/138368 (1.88).

  - [x] Longstanding issue affecting Klint.
    + > `if let Some(bar) = foo {}` will now prevent `drop(foo)` being added at the end of scope. This might allow me to try run klint on binder again.
    + Issue: https://github.com/rust-lang/rust/issues/142705.
    + PR: https://github.com/rust-lang/rust/pull/142707 (1.90).
    + Cc: @nbdd0121.

  - [x] Adding flags directly as `-C` instead of `-Z` (requiring `-Zunstable-options` to use them) to avoid churn in downstream projects like Rust for Linux.
    + The proposal didn't move and was dropped.
    + MCP: https://github.com/rust-lang/compiler-team/issues/787.

  - [x] Mitigation enforcement (`-Zallow-partial-mitigations`).
    + Moved into the main list since it got implemented.
    + Tracking Issue: https://github.com/rust-lang/rust/issues/154613.
    + Similar to target modifiers, but for mitigations (see "Why not target modifiers?" in the RFC).
    + Also called `#![feature(mitigation_enforcement)]` in the RFC, but not used like that.
    + RFC: https://github.com/rust-lang/rfcs/pull/3855.
    + PR: https://github.com/rust-lang/rust/pull/149357 (1.97).

---

### Required (we almost certainly want them)

  - [ ] The `-softfloat` target does not have KCFI nor KASAN enabled.
    + Starting with Rust 1.85.0, we are supposed to use the `-softfloat` target to avoid the warning avoid disabling `neon` in the non-softfloat one, because it warns (without the ability to silence it) and will be a hard error eventually.
    + Issue in Zulip: https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/arm64.20neon.20.60-Ctarget-feature.60.20warning/near/495358442.
    + PR: https://github.com/rust-lang/rust/pull/135905 (1.86).
    + Backport to beta PR: https://github.com/rust-lang/rust/pull/136650 (1.85 since `rustc 1.85.0-beta.8 (38213856a 2025-02-06)`).

  - [ ] `-Zregparm` doesn't put 64-bit arguments in registers.
    + Issue: https://github.com/rust-lang/rust/issues/145694.
    + PR: https://github.com/rust-lang/rust/pull/147628.

  - [ ] MIR optimization produces worse code by losing aliasing information.
    + Issue with `build_assert!` within `write32` not working due to `pr_err!` call in-between.
    + Lore: https://lore.kernel.org/rust-for-linux/20250920161958.2079105-1-joelagnelf@nvidia.com/.
    + Issue: https://github.com/rust-lang/rust/issues/146844.
    + LLVM PR: https://github.com/llvm/llvm-project/pull/160913.
    + Cc: @joelagnel @nbdd0121.

  - [ ] Unsafe macros inside `unsafe fn`s do not respect `-Dunsafe_op_in_unsafe_fn`.
    + For instance, our `container_of!` can be called without an `unsafe` block (and no `// SAFETY: ...` comment) within an `unsafe fn`.
    + The issue does not happen within the same crate, only if the macro is exported.
    + Issue: https://github.com/rust-lang/rust/issues/112504.
    + Zulip: https://rust-for-linux.zulipchat.com/#narrow/channel/288089-General/topic/Nightly.20Features.20for.20LinkedList.3F/near/555572870.
    + Lore: https://lore.kernel.org/rust-for-linux/20251114140020.327075-2-phasta@kernel.org/.

  - [ ] Improved Edition migration tooling (2021 -> 2024).
    + We are considering migrating from Edition 2021 to 2024, but for that we will need to make sure the tooling that checks for behavior changes has no false negatives, because we would need to use it for checking backports into stable/LTS branches of the Linux kernel that use the older Edition.
    + Issue: https://github.com/rust-lang/rust/issues/155010.
    + Issue: https://github.com/rust-lang/rust-clippy/issues/16827.

### Nice to have (probably not critical, we could workaround if needed, etc.)

  - [ ] Include all (i.e. non-code-related) warnings in `-Dwarnings` (or include a way to control whether they are errors).
    + Issue: https://github.com/rust-lang/rust/issues/91262.
    + MCP: https://github.com/rust-lang/compiler-team/issues/473.

  - [ ] Finish `unreachable_pub` lint implementation.
    + Issue: https://github.com/rust-lang/rust/issues/64762.
    + Issue: https://github.com/rust-lang/rust/issues/82064.

  - [ ] `--emit=dep-info` + `-Zunpretty=expanded` emits output.
    + Issue: https://github.com/rust-lang/rust/issues/93201.

  - [ ] Missed optimization (`to_result` discussion).
    + From: https://lore.kernel.org/rust-for-linux/CANiq72nO=Eje0dv_NCagvTzOLU7WkfM-bwqH33z_kC=f=m1m1A@mail.gmail.com/
    + Issue: https://github.com/rust-lang/rust/issues/116150.
    + Issue in LLVM: https://github.com/llvm/llvm-project/issues/67342.

  - [ ] Missed optimization (wrapping "raw generated `enum`s into cleaner ones).
    + From: https://lore.kernel.org/rust-for-linux/CANiq72nCJc6wL1VY9=8A5NruY++8X4db+agpC-SW2MMiuyduHA@mail.gmail.com/
    + Issue: https://github.com/rust-lang/rust/issues/116272.
    + Issue in LLVM: https://github.com/llvm/llvm-project/issues/67842.
    + Issue in LLVM: https://github.com/llvm/llvm-project/issues/67843.
    + PR in LLVM: https://github.com/llvm/llvm-project/pull/67881.
    + PR in LLVM: https://github.com/llvm/llvm-project/pull/67882.

  - [ ] `rustc_parser` incorrectly parses groups with `Delimiter::None` .
    + Issue: https://github.com/rust-lang/rust/issues/67062.
    + Lore: https://lore.kernel.org/rust-for-linux/DGUAE329P4FH.3QPNCVLNA99MC@garyguo.net/.

### Low priority (we will likely not use them in the end)

  - [ ] `rustc` warns when finding an unknown jobserver style.
    + Non-critical for us, since we should be able to update `rustc` (or users could force an older jobserver style).
    + Issue: https://github.com/rust-lang/rust/issues/120532.

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] creader: Host crate loaded twice produces different `CrateNum`s if host != target.
    + Issue: https://github.com/rust-lang/rust/issues/56935.
    + PR: https://github.com/rust-lang/rust/pull/86876.

  - [x] Skip linking if it is not required.
    + PR: https://github.com/rust-lang/rust/issues/81118.

  - [x] ICE when proc macro panics if compiled with `-Cpanic=abort`.
    + Issue: https://github.com/rust-lang/rust/issues/82320.
    + PR: https://github.com/rust-lang/rust/pull/106678.

  - [x] Set `dso_local` for hidden, private and local items.
    + PR: https://github.com/rust-lang/rust/pull/83592.

  - [x] Set `dso_local` for more items.
    + PR: https://github.com/rust-lang/rust/pull/85276.

  - [x] Add back support for `inline` `stack-probes`.
    + LLVM: https://bugs.llvm.org/show_bug.cgi?id=50165.
    + Issue: https://github.com/rust-lang/rust/issues/43241.
    + Issue: https://github.com/rust-lang/rust/issues/84667.
    + Related: https://github.com/rust-lang/rust/pull/77885.
    + Related: https://github.com/rust-lang/rust/issues/74405.
    + Related: https://github.com/rust-lang/rust/pull/118491.

  - [x] Strange `-Zunpretty=expanded` behavior with `global_asm!`.
    + Issue: https://github.com/rust-lang/rust/issues/101047.
    + Issue: https://github.com/rust-lang/rust/issues/101051.
    + PR: https://github.com/rust-lang/rust/pull/101369.

  - [x] The `x86_64-unknown-none-linuxkernel` target is not actually used.
    + PR: https://github.com/rust-lang/rust/pull/104015.

  - [x] ARM64: Fix some issues with folded AArch64 features.
    + Lore: https://lore.kernel.org/rust-for-linux/20230125163739.3798252-1-Jamie.Cunliffe@arm.com/.
    + PR: https://github.com/rust-lang/rust/pull/107294.

  - [x] Ensure 128-bit types from the C side (`__int128_t`, `__uint128_t`) are usable for architectures that need it.
    + For ARM64, `i128`/`u128` match the ABI of the C ones, and that should remain the case thanks to https://github.com/rust-lang/libc/pull/2719.
    + Issue: https://github.com/rust-lang/rust/issues/54341.
    + Issue: https://github.com/rust-lang/lang-team/issues/255.
    + Status: https://github.com/rust-lang/rust/issues/54341#issuecomment-2059486433.
    + Lore: https://lore.kernel.org/rust-for-linux/Bs9NB9XuVGuOkEvvTFpYIPDo-S-bn6LpsSKciLfFkp5J73L84wAsJFXGKYEZ7VtCKYIWUWyKxvtelgi7NuvcDT6kgPXGiz8VoUv6gh-fFGQ=@protonmail.com/.

  - [x] `.eh_frame` section emitted for `kernel.o` (debug assertions enabled, `rustc` >= 1.70.0).
    + Issue: https://github.com/Rust-for-Linux/linux/issues/1012.
    + PR: https://github.com/rust-lang/rust/pull/112403 (1.72).

  - [x] `.eh_frame` section emitted for `rust_echo_server.o`.
    + Issue: https://github.com/Rust-for-Linux/linux/issues/1016.
    + PR: https://github.com/rust-lang/rust/pull/113124 (1.73).

  - [x] `-Zunpretty=expanded` does not emit `dep-info` anymore (1.68 -> 1.69).
    + Issue: https://github.com/rust-lang/rust/issues/112898.
    + PR: https://github.com/rust-lang/rust/pull/114476 (1.73).

  - [x] `#[expect(dead_code)]` does not behave identically to `#[allow(dead_code)]`.
    + Issue: https://github.com/rust-lang/rust/issues/114557.
    + PR: https://github.com/rust-lang/rust/pull/114710 (1.73).

  - [x] 1.74 ICE.
    + Seen in the Asahi AGX kernel driver.
    + Solved in 1.74.1.
    + Issue: https://github.com/rust-lang/rust/issues/117976.
    + Marked for stable backport: https://github.com/rust-lang/rust/pull/116415.

  - [x] `rustc` 1.76 (beta) warns about non-recursive invocation from Make.
    + `rustc` may document that it may always take advantage of the jobserver (e.g. for backend and eventually frontend parallelism), and thus users should always call `rustc` as recursive from Make.
    + Issue: https://github.com/rust-lang/rust/issues/120515.
    + PR: https://github.com/rust-lang/rust/pull/121564 (1.80).

  - [x] The last `--jobserver-auth` flag should be used like the GNU Make manual asks to (`jobserver` crate, used by `rustc`).
    + Non-critical for us, since kernel developers should not be touching the flag manually or using something that is not GNU Make.
    + Issue: https://github.com/rust-lang/jobserver-rs/issues/66.
    + PR (`jobserver`): https://github.com/rust-lang/jobserver-rs/pull/67.
    + PR: https://github.com/rust-lang/rust/pull/120846 (1.77).

  - [x] `rustc` should disable the jobserver if file descriptors are negative like the GNU Make manual asks to.
    + Non-critical for us, since even if a user requests the older jobserver style, we will be marking all `rustc` calls as recursive.
    + Kernel users should not see this unless they request in Make 4.4 the older jobserver style for some reason.
    + Issue: no separate issue; from https://github.com/rust-lang/rust/issues/120515.
    + PR (`jobserver`): https://github.com/rust-lang/jobserver-rs/pull/68.
    + PR: https://github.com/rust-lang/rust/pull/120846 (1.77).

  - [x] ICE on `rustc 1.79.0-beta.4 (a26981974 2024-05-10)` when compiling `core.o`.
    + Reproducer: `RUSTC_BOOTSTRAP=1 rustc --edition=2021 -Csymbol-mangling-version=v0 --cfg no_fp_fmt_parse --crate-type rlib library/core/src/lib.rs --sysroot=/dev/null`.
    + Related PR (beta nominated): https://github.com/rust-lang/rust/pull/123816 (1.79).
    + Issue: https://github.com/rust-lang/rust/issues/125229.
    + PR (beta nominated): https://github.com/rust-lang/rust/pull/125252 (1.79).
    + PR: https://github.com/rust-lang/rust/pull/125529 (1.79).
    + Fixed in `rustc 1.79.0-beta.7 (d9e85b56e 2024-05-25)`.
    + Cc: @tgross35.

  - [x] Are attributes such as `noalias`, `readonly`, `dereferenceable`... worth it for performance or could they potentially be all disabled to get something like `-fno-strict-aliasing`?
    + Perf run: https://github.com/rust-lang/rust/pull/137707.

  - [x] Fix `-Zremap-path-scope`.
    + Issue: https://github.com/rust-lang/rust/issues/148328.
    + PR: https://github.com/rust-lang/rust/pull/149709 (1.94).
    + Lore: https://lore.kernel.org/rust-for-linux/DG93P7TMCWCH.3ACJU31B2HELW@garyguo.net/.

  - [x] Miscompilation on ppc64.
    + It is an LLVM bug, present only in LLVM 22.
    + LLVM fix: https://github.com/llvmbot/llvm-project/commit/4bab6aacf6b3fe7465a0a4a75b09de0aad2c726f (22.1.9?).
    + Issue: https://github.com/rust-lang/rust/issues/151807.
    + Issue: https://github.com/rust-lang/rust/issues/152177.
    + Lore: https://lore.kernel.org/rust-for-linux/aYS2oWCE0ZCC3don@li-1a3e774c-28e4-11b2-a85c-acc9f2883e29.ibm.com/.
    + PR: https://github.com/rust-lang/rust/pull/152428 (1.95).

  - [x] `lint_reasons` + `unused_features` interaction.
    + We may just `allow` the lint.
    + Issue: https://github.com/rust-lang/rust/issues/153523.
    + PR: https://github.com/rust-lang/rust/pull/153610 (1.96).
