### ISSUE TITLE
`rustup` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#396]
### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Support `.rust-toolchain.toml`.
    + From: https://github.com/Rust-for-Linux/linux/issues/953.
    + Issue: https://github.com/rust-lang/rustup/issues/3182.
    + PR: https://github.com/rust-lang/rustup/pull/3195.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Clarify in which component and/or profile `rustdoc` is.
    + Issue: https://github.com/rust-lang/rustup/issues/2801.
    + PR: https://github.com/rust-lang/rustup/pull/2805.

  - [x] Downloading specific betas should be easier.
    + Issue: https://github.com/rust-lang/rustup/issues/1329.
