### ISSUE TITLE
`core` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#514]
Note: there is the "A-rust-for-linux" label in the `rust` repository: https://github.com/rust-lang/rust/labels/A-rust-for-linux.

### Required (we almost certainly want them)

  - [ ] Disabling atomics (i.e. only allowing the LKMM ones introduced in v6.18 in the `kernel` crate).
    + Part of the "modularization of `core`" topic.

  - [ ] Guaranteeing `TypeId`'s size is at most 16 bytes.
    + PR: https://github.com/rust-lang/rust/pull/148265.
    + Meeting Proposal: https://github.com/rust-lang/compiler-team/issues/941.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/channel/425075-rust-for-linux/topic/TypeId.20layout.
    + Zulip: https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/TypeID.20design.

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] Disabling 128-bit features.
    + Part of the "modularization of `core`" topic.
    + PR: https://github.com/rust-lang/rust/pull/103126.
    + PR: https://github.com/rust-lang/rust/pull/136385.

  - [ ] Disabling floating-point features.
    + Part of the "modularization of `core`" topic.
    + Currently we provide weak symbols that panics, but generally we should not even compile floating point support (in the kernel, very little code needs it, and it is compiled differently in the C side). Ideally, we would have a compiler flag to disable all that where not needed (possibly even not accepting code referring to `f32` etc.).
        > Maybe we should add a check, perhaps by compiling against softfp and link against compile-rt with hardfp to see if no symbols are unresolved?
    + Cc: @nbdd0121.
    + PR (a `cfg` to disable formatting of floating point): https://github.com/rust-lang/rust/pull/86048.

  - [ ] Disabling Unicode features / a way to use external tables.
    + Part of the "modularization of `core`" topic.

  - [ ] Clarify invariants of the `Layout` type.
    + i.e. lift requirements to the type from the constructors / how does one connect `Layout` to "a layout suitable to an allocated object"? Is it library / language UB? (currently it appears to be the former).
    + After https://github.com/rust-lang/rust/pull/116675, a reference could be added to that from `Layout` type documentation.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Document.20.60Layout.60.20Type.20Invariant.3F/near/412607198.
    + From: discussion in Rust for Linux Zulip between Valentin, Benno and Miguel.
    + Related issue in UCG: https://github.com/rust-lang/unsafe-code-guidelines/issues/465.
    + Related PR: https://github.com/rust-lang/rust/pull/95295.

  - [ ] `c_stringify!`, `c_concat!`, `c_file!` macros.
    + Instead of having to provide a `c_str!` macro to then do `c_str!(stringify!(...))` or `c_str!(concat!(...))`.
    + Lore: https://lore.kernel.org/rust-for-linux/CANiq72nbbtNp4vGGHkXVSgSW+WU=5Z9uGRO_LLg7+ezTqrZ_tQ@mail.gmail.com/
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/stream/404510-wg-macros/topic/May.20we.20need.20a.20.60c_stringify!.60.20and.20.60c_concat!.60.20macros.3F/near/466691443.
    + Cc: @vincenzopalazzo @y86-dev.
    + It could prevent mistakes where one assumes it is nul-terminated, perhaps disallowing the usual one in Clippy: https://lore.kernel.org/rust-for-linux/20241016035214.2229-8-fujita.tomonori@gmail.com/#iZ31rust:kernel:io:poll.rs.

  - [ ] Clarify `addr_of!` documentation about whether it creates read-only pointers or not.
    + From: https://github.com/Rust-for-Linux/linux/pull/950#discussion_r1104311862.
    + PR: https://github.com/rust-lang/rust/pull/129653.

  - [ ] Moving towards `core::ffi::CStr` (from `kernel::str::CStr`).
    + Rust for Linux Issue: https://github.com/Rust-for-Linux/linux/issues/1075.
    + PR: https://github.com/rust-lang/rust/pull/138498.
    + `impl Display for CStr` ACP: https://github.com/rust-lang/libs-team/issues/550.
    + `impl Display for CStr` Tracking Issue: https://github.com/rust-lang/rust/issues/139984.
    + `impl Display for CStr` PR: https://github.com/rust-lang/rust/pull/139994.
    + `ByteStr` Tracking Issue: https://github.com/rust-lang/rust/issues/134915.
    + Related PR: https://github.com/rust-lang/rust/pull/136687.
    + Lore ("rust: replace kernel::str::CStr w/ core::ffi::CStr"): https://lore.kernel.org/rust-for-linux/20250317-cstr-core-v9-0-51d6cc522f62@gmail.com/.
    + Lore (Gary's suggestion): https://lore.kernel.org/all/20250221142816.0c015e9f@eugeo/.

  - [ ] `container_of!` in the standard library.
    + Currently we use our own implementation.

### Low priority (we will likely not use them in the end)

  - [ ] Generic atomics.
    + We are considering whether to use a generic API for our atomics, thus we will be watching any progress on the `core` ones.
    + Issue: https://github.com/rust-lang/rust/issues/130539.
    + ACP (API Change Proposal): https://github.com/rust-lang/libs-team/issues/443.
    + Initial PR: https://github.com/rust-lang/rust/pull/130543.
    + PR: https://github.com/rust-lang/rust/pull/136316 (1.88).
    + LPC Rust MC topic: https://lpc.events/event/18/contributions/1788/
    + Cc: @fbq.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Ensure `no_fp_fmt_parse` builds are warning-free.
    + PR: https://github.com/rust-lang/rust/pull/105811.

  - [x] Ensure `no_global_oom_handling` builds are warning-free.
    + PR: https://github.com/rust-lang/rust/pull/110652.

  - [x] C string equivalents (nul-terminated) for `core::panic::Location` (or a flag to ensure there is a `\0` after the `str`s).
    + Moved to the main list: `feature(location_file_nul)`.
    + Tracking Issue: https://github.com/rust-lang/rust/issues/141727.
    + For the macros like `file!()`, it is fine, since we can easily transform those with `c_str!` (which we already do), so it is a nice to have (see the related item below).
    + Lore: https://lore.kernel.org/rust-for-linux/CAH5fLgjk5koTwMOcdsnQjTVWQehjCDPoD2M3KboGZsxigKdMfA@mail.gmail.com/.
    + Rust Zulip: https://rust-lang.zulipchat.com/#narrow/stream/425075-rust-for-linux/topic/Caller.20location.20with.20nul-terminated.20filename/near/477164522.
    + ACP: https://github.com/rust-lang/libs-team/issues/466 (accepted).
    + PR: https://github.com/rust-lang/rust/pull/135054 (1.89).
    + PR: https://github.com/rust-lang/rust/pull/135240.
    + PR: https://github.com/rust-lang/rust/pull/131828.
    + PR: https://github.com/rust-lang/rust/pull/117431.

  - [x] `feature(int_lowest_highest_one)`, i.e. `{highest,lowest_one}` (`{first,last}_set_bit`) for integer types.
    + Moved to the main list: `feature(int_lowest_highest_one)`.
    + Tracking Issue: https://github.com/rust-lang/rust/issues/145203.
    + PR: https://github.com/rust-lang/rust/pull/145381 (1.91).
    + ACP (API Change Proposal): https://github.com/rust-lang/libs-team/issues/631.
    + Lore: https://lore.kernel.org/rust-for-linux/DAREXAUV51B6.7X7TPOJKK249@nvidia.com/.
    + Cc: @Gnurou.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] https://github.com/rust-lang/rust/pull/105434.

  - [x] Fix `no_global_oom_handling` build.
    + PR: https://github.com/rust-lang/rust/pull/110649.

  - [x] Inline floating-point methods to avoid requiring intrinsics.
    + `midpoint`, `next_up`, `next_down` are not marked as `#[inline]`, which makes them appear under `-Os` arm64, see Zulip: https://rust-for-linux.zulipchat.com/#narrow/stream/288089-General/topic/v6.2E11-rc1.20doesn't.20build.20for.20arm64/near/455637364.
    + PR: https://github.com/rust-lang/rust/pull/128749.

  - [x] CFI failure on `core::fmt::write()` when FineIBT is enabled.
    + Issue: https://github.com/rust-lang/rust/issues/115199.
    + PR (point 2 of the issue above): https://github.com/rust-lang/rust/pull/139632 (1.88).
    + PR (previous approach): https://github.com/rust-lang/rust/pull/115954.
    + Patch to restrict FineIBT with Rust: https://lore.kernel.org/rust-for-linux/20250410115420.366349-1-panikiel@google.com/.

**Comment by bjorn3** [comment]
> Disabling futures features.

I could only find a single function that is neither generic nor `#[inline]` for the future handling. This function is very small, so disabling futures in libcore will barely save any space. Generic and `#[inline]` functions are only codegened when actually used. All disabling futures will do is prevent someone from deliberately using futures and possibly for the current rustc version cause an ICE when trying to use `async fn`. (haven't checked though)

**Comment by fbq** [comment]
> > Disabling futures features.
> 
> All disabling futures will do is prevent someone from deliberately using futures and possibly for the current rustc version cause an ICE when trying to use `async fn`. (haven't checked though)

Right! I'm experimenting implementing two `Context`s backed by the mechanisms of Linux kernel to `poll` `Futures`:

* A kernel thread, `Future` `poll`ed in thread functions and `wake` means wake up a kernel thread. (I already have a working version)
* A work item in workqueue, `Future` `poll`ed in work functions and `wake` means requeue the work item in the workqueue. (Still need to figure out some `safe` abstraction, but it works in theory).

`Future` may help kernel developers to refactor (rethink) some async work, so I think it's very important that we support it.

**Comment by ojeda** [comment]
> I could only find a single function that is neither generic nor `#[inline]` for the future handling. This function is very small, so disabling futures in libcore will barely save any space. Generic and `#[inline]` functions are only codegened when actually used. All disabling futures will do is prevent someone from deliberately using futures and possibly for the current rustc version cause an ICE when trying to use `async fn`. (haven't checked though)

This came from the original list I had in the other issue, where they were examples of the general idea of partitioning `core`. I agree that it does not make much sense to list it now that they are split as actual items we would like. Removed!

**Comment by GKFX** [comment]
I have opened a PR to remove 128-bit features: https://github.com/rust-lang/rust/pull/103126.

**Comment by ojeda** [comment]
Thanks! Added.

**Comment by workingjubilee** [comment]
Before we add more `cfg`, if the goal is mostly a smaller text size, then can we look at just... trying to optimize the actual sizes of things? https://github.com/rust-lang/rust/pull/109216 got a win of ~24KiB in size (and faster, mostly!) by taking a swing at that.

Adding configuration code doesn't necessarily affect statically linked binaries as much, as those will either be stuck with the code also, for each that actually uses it, or dead-code-eliminate it, and statically linked binaries include some of the use-cases that want the smallest size (such as embedded code which isn't running on an OS at all, not even an RTOS, and thus has limited options for dynamic linking and is usually just one blobby image).

**Comment by tgross35** [comment]
This may come in handy at some point down the line https://github.com/Amanieu/rfcs/blob/core-detect/text/0000-core_detect.md

**Comment by fbq** [comment]
Following up the discussion [here](https://lore.kernel.org/rust-for-linux/ZWipTZysC2YL7qsq@Boquns-Mac-mini.home/), I'd like to add two `asm` wanted features:

* [asm goto (or jump to a label)](https://rust-lang.github.io/rfcs/2873-inline-asm.html#asm-goto), this is required by the [static key](https://docs.kernel.org/staging/static-keys.html)
* [memory operand](https://rust-lang.github.io/rfcs/2873-inline-asm.html#memory-operands), this would allow generate more efficient code, and it's currently supported by inline asm of gcc and clang, and used by Linux kernel. 

Although @nbdd0121 mentioned these should be `lang` feature instead of `core` feature. But I haven't found a `lang` feature issue. Feel free to put it wherever you see fit ;-)

**Comment by ojeda** [comment]
Sounds good, thanks! Language features are in https://github.com/Rust-for-Linux/linux/issues/354 (I had `asm goto` there already, added memory operands too now).

**Comment by BennoLossin** [comment]
@ojeda about the `c_stringify!` macro, we should probably ask the libs team, since that would be their area.

**Comment by ojeda** [comment]
+1, I think @vincenzopalazzo wanted to mention it to the macros working group too.

**Comment by tgross35** [comment]
In theory the new macro metavar expression `${concat(c, $str)}` might be able to handle it where needed.

**Comment by vincenzopalazzo** [comment]
I finally had the time to start discussing the `c_stringify!` on the wg-macros, if you would like to follow it, please [see the zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/404510-wg-macros/topic/May.20we.20need.20a.20.60c_stringify!.60.20and.20.60c_concat!.60.20macros.3F)

**Comment by ojeda** [comment]
Thanks! Added.
