### ISSUE TITLE
`std` wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#572]
Note: there is the "A-rust-for-linux" label in the `rust` repository: https://github.com/rust-lang/rust/labels/A-rust-for-linux.

### Low priority (we will likely not use them in the end)

  - [ ] Make `test` not depend on `std`.
    + TODO: try out `#![test_runner]` + `#![reexport_test_harness_main]` as suggested by @bjorn3: https://github.com/Rust-for-Linux/linux/issues/572#issuecomment-980636107.
    + It would require customizing whatever `test` needs from `std` at the moment.
    + It would avoid having to build `std` for tests.
    + It would allow to run tests in kernel space ("`#[test(kernel)]`").
    + It would avoid having to wait for Cargo's `-Zbuild-std` fixes & stabilization.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] A way to customize/override the dependency graph in `-Zbuild-std` to use our custom `alloc` etc.
    + `alloc` was dropped, so we do not need it anymore.
    + Related issue: https://github.com/rust-lang/wg-cargo-std-aware/issues/7.
    + Related issue: https://github.com/rust-lang/wg-cargo-std-aware/issues/61.

  - [x] A way to use `-Zbuild-std` for building custom sysroots (and not packages).
    + We do not use `-Zbuild-std` anymore.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

**Comment by bjorn3** [comment]
> Make test not depend on std.

For no-std testing there is the unstable `#![test_runner]` + `#![reexport_test_harness_main]`. This was implemented in https://github.com/rust-lang/rust/pull/53410. See https://os.phil-opp.com/testing/ for an example. To copy the example there:

```rust
#![feature(custom_test_frameworks)]
#![test_runner(crate::test_runner)]
#![reexport_test_harness_main = "test_main"]

#[cfg(test)]
fn test_runner(tests: &[&dyn Fn()]) {
    println!("Running {} tests", tests.len());
    for test in tests {
        test();
    }
}

#[no_mangle]
pub extern "C" fn _start() -> ! {
    println!("Hello World{}", "!");

    #[cfg(test)]
    test_main();

    loop {}
}

#[test_case]
fn trivial_assertion() {
    print!("trivial assertion... ");
    assert_eq!(1, 1);
    println!("[ok]");
}
```

I believe I have already linked it before by the way.

**Comment by ojeda** [comment]
Thanks! I think you did, yeah. Linked in the list to avoid missing it again :)

I was filling this one to keep track of some of the bits from the meeting the other day that were not yet in the list.
