### ISSUE TITLE
KernelCI wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#927]
### Required (we almost certainly want them)

  - [ ] Automatically determining the right Rust version to use.
    + The kernel currently only supports one Rust version at a time. It would be great to support several Rust versions at a time so that the right one is picked to compile a given kernel.
    + Apparently hard to do in the legacy system, but perhaps it is possible to have a single "universal" image with a `rustc` binary that redirects to the right one. In other words, for the purposes of KernelCI, Rust would have a single toolchain version.

  - [ ] Enable KUnit tests.
    +  i.e. `CONFIG_RUST_KERNEL_DOCTESTS`.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Rust support.
    + Issue: https://github.com/kernelci/kernelci-core/issues/814.
    + PR: https://github.com/kernelci/kernelci-core/pull/1468.

  - [x] Rust 1.66.0.
    + PR: https://github.com/kernelci/kernelci-core/pull/1597.

  - [x] Disable IBT/Retpoline/Rethunk.
    + Issue: https://github.com/Rust-for-Linux/linux/issues/945.
    + PR: https://github.com/kernelci/kernelci-core/pull/1580.

  - [x] Rust 1.68.2.
    + PR: https://github.com/kernelci/kernelci-core/pull/1890.
    + PR: https://github.com/kernelci/kernelci-core/pull/1926.

  - [x] Rust 1.71.1 and `bindgen` 0.65.1.
    + PR: https://github.com/kernelci/kernelci-core/pull/2039.

  - [x] Rust 1.72.0 and delete `rust-for-linux_rust` build config.
    + PR: https://github.com/kernelci/kernelci-core/pull/2068.

  - [x] Rust 1.73.0.
    + PR: https://github.com/kernelci/kernelci-core/pull/2124.

  - [x] Rust 1.74.1.
    + PR: https://github.com/kernelci/kernelci-core/pull/2250.

  - [x] Rust 1.75.0.
    + PR: https://github.com/kernelci/kernelci-core/pull/2321.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

**Comment by aliceinwire** [comment]
@ojeda both PR merged. thanks
