### ISSUE TITLE
Compiler Explorer wanted features & bugfixes

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#949]
### Required (we almost certainly want them)

  - [ ] `bindgen` support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/4554.

  - [ ] `rustfmt` support (i.e. as a compiler or perhaps versioned CE tool).
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/4553.

### Nice to have (not critical, we could workaround if needed, etc.)

  - [ ] Pre-filling flags (e.g. `--edition` for Rust) instead of compiler overrides' implicit approach.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3765.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3100.
    + Related issue: https://github.com/compiler-explorer/compiler-explorer/issues/5349.
    + Related issue: https://github.com/compiler-explorer/compiler-explorer/issues/5429.

  - [ ] Support overriding all flags on the command line (i.e. support multiple `--target`, `--sysroot`, `--edition`...).
    + See the item of the same title at https://github.com/Rust-for-Linux/linux/issues/355.

  - [ ] Augmenting compiler diagnostics with hyperlinks and custom actions.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/5284.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/3895.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7318.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7357.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/8354.

  - [ ] Enable additional useful tools.
    + https://github.com/compiler-explorer/compiler-explorer/issues/6650.

### Done (stabilized, fixed, not needed anymore, etc.)

  - [x] Enable additional tools that are available for C and C++.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/6796.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7264.

  - [x] Code formatting support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2564.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2798.

  - [x] MIR output support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2566.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2795.

  - [x] HIR output support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2567.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/3147.

  - [x] Macro expansion support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2568.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2932.

  - [x] `mrustc` compiler support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2643.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2681.

  - [x] Rust GCC (i.e. `gccrs`) support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2644.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2628.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2632.

  - [x] `rustc_codegen_gcc` backend support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2683.
    + PR: https://github.com/compiler-explorer/misc-builder/pull/6.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/2746.

  - [x] Allow using unstable features in all compilers.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2724.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3154.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/4151.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/5001.

  - [x] Default to the latest available Rust edition.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3765.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/3100.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/5001.

  - [x] Clippy support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2562.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7477.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7497.

  - [x] C2Rust support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/5900.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/6888.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7475.

  - [x] Miri support.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/2563.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/7718.
    + PR: https://github.com/compiler-explorer/infra/pull/1630.
    + PR: https://github.com/compiler-explorer/infra/pull/1631.
    + PR: https://github.com/compiler-explorer/misc-builder/pull/112.
    + PR: https://github.com/compiler-explorer/misc-builder/pull/113.
    + PR: https://github.com/compiler-explorer/compiler-workflows/pull/36.

  - [x] Support "Compile to binary object" for multiple architectures.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/5593.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/8460.

---

### Done (stabilized, fixed, or not needed anymore, etc.)

  - [x] Rust links that included the `--edition` flag broke with compiler overrides.
    + Issue: https://github.com/compiler-explorer/compiler-explorer/issues/5429.
    + PR: https://github.com/compiler-explorer/compiler-explorer/pull/6789.
